== Prefatory Remarks.

The following narrative concerning Rebecca Hubbs conveys an instructive
account of one of but little literary talent or culture,
awakened from the seductive vanities of time and sense,
and so quickened and brought into obedience to the
teaching and sanctifying power of the grace of God,
as to become a worthy instrument in his hand towards the promotion of the kingdom
of his dear Son in the hearts of those where her lot was cast.

The writer of this preface well remembers her lack of ability for even ordinary,
much less for literary conversation,
because of her difficulty in making herself understood.
This was associated with a very humble view of herself in every way.
Nevertheless, when she felt herself called to advocate the gospel of Jesus her Saviour,
her ministry savored richly of the power of the anointing;
conveyed "`not in the words which man`'s wisdom teaches,
but which the Holy Spirit teaches.`"
For she neither received it of man,
neither was she taught it but by the revelation of Jesus Christ.
She was indeed a remarkable instance of the all-sufficient
grace and immediately qualifying power of the Redeemer,
independently of human wisdom and learning;
and was an illustration of the truth of the Scripture declaration:
"`God has chosen the foolish things of the world to confound the wise;
and God has chosen the weak things of the world to confound the things which are mighty;
and base things of the world, and things which are despised, has God chosen, yes,
and things which are not, to bring to nought things that are;
that no flesh should glory in his presence.`"

Thus, through obedience to "`the hidden wisdom,`" though
very deficient in the learning of the schools,
Rebecca Hubbs became a dignified instrument--prepared by the immediate
power of Him that called her--in upholding the standard of righteousness,
and in calling others to come, taste, and see that the Lord is good.
