== The Life of Rebecca Hubbs

It is encouraging, as well as instructive,
to trace the blessed effects which result from a submission
of the heart to the transforming power of Divine Grace;
to observe how it compensates for the want of outward advantages,
brightens and sanctifies the intellectual faculties, and supplies,
in a remarkable manner, by the wisdom which cometh from above,
the absence of that which belongs to the men of this world.
It is true that, as respects temporal affairs, "`the children of this world are often,
in their generation,
wiser than the children of light;`" but in those
things that relate to the great business of life,
the salvation of the soul, the wise and the simple, the learned and the ignorant,
the high and the low, the rich and the poor, by walking in the light,
and following whither it leads, are all placed on equal ground.

Many are the instances in our own religious Society where those who have been providentially
placed in circumstances peculiarly unfavorable to a religious life,
surrounded by strong temptations to evil,
and destitute of any instrumental help to encourage them in a life of holiness, have yet,
through obedience to the merciful visitations of the Saviour of sinners,
experienced preservation from wrong things,
been clearly instructed in the way and work of salvation, and,
by humbly and steadily persevering therein,
have been made useful instruments in promoting the Lord`'s cause, though naturally weak,
and without the benefit of much literary instruction.
Baptized by this one Spirit into one body, and governed by the one adorable Head,
Christ Jesus, every member, even the least and lowest, has its place and service,
and those who are much out of sight, and may be esteemed the least comely,
are necessary to the harmonious and perfect action of the whole,
as well as those who are more conspicuous, or accounted more honorable;
each contributing its share to the good of the whole, and the honor of the great Head.

There is no religious body whose principles and organization are so calculated
to show forth the beautiful and harmonious working of these views,
under the guidance of the Holy Spirit, as the Society of Friends;
because none recognize in the same manner the free exercise of those gifts
which are conferred on every faithful member of the church;
gifts differing according to the measure of each,
and to the will of the Sovereign Dispenser, but all to be exercised in due order,
and with condescension one to another.

Rebecca Hubbs was the daughter of Paul and Rebecca Crispin,
and was born the 3rd of the Twelfth month, 1772.
Her ancestors, on both sides, had been members of the Society of Friends,
and appear to have suffered for the maintenance of their Christian principles,
but it does not appear that her parents had a right of membership among them.
She remarks, in some memorandums which she made:
"`From my first acquaintance with the names and character of my predecessors,
my mind was impressed with reverence and holy fear,
having learned that they shared with others in the persecutions and sufferings
of the early Friends for their testimony to Jesus Christ,
the Saviour of the world, and for the cause of Truth.`"

It would seem to have been her intention to prepare
an account of her life and religious experience;
but she wrote very little,
and but few circumstances of her early years can now be collected.
Her own narrative commences thus:

[.small-break]
'''

"`Tenth month, 1812.
"`Come and hear, all ye that fear God, and I will declare what He hath done for my soul.`"
Ps. 66:16.
When I look back on my past life,
and the many dangers which have surrounded me;
through all which the arm of Divine goodness and mercy has been near to protect me,
a poor creature, who feels unworthy of the least of all the Lord`'s mercies,
the language of my heart is; "`While life remains, may that love never wear away,
which is his due from me, whom He has been pleased to make a monument of his mercy.`"
It has, for a length of time,
seemed to be due from me to the God of my life to
leave some little memorial of his mercies to me,
yet I have omitted it,
concluding my weak sound of praises to the Lord would not
be heard among those of the many valiants in Israel.
But thinking it may be a satisfaction to my children,
I leave these few lines for their serious consideration, desiring they may read them,
and be benefited thereby, when my body lies sleeping in the grave,
and my spirit is entered into rest, as I hope it will, when it may join in praising Him,
who is forever worthy.
Amen.

"`I lived with my parents, in the village of Moorestown, N. J.,
and well remember that when a little child,
I had very serious thoughts on death and the world to come.
But my parents lived after the common customs of the world,
and did not enough feel the necessity of restraining their
children from those things which often corrupt the mind.
I learned to sing, and was delighted with it; and, if I recollect right,
it was about the eighth or ninth year of my age,
when my indulgent father received into his house a person
who played on an instrument of music called a dulcimer.
He remained with us several months,
during which time he taught me to play on the instrument,
although I was such a little girl as scarcely to be able
to reach my dulcimer when it was laid on the dining-table.

"`As I advanced towards the eleventh or twelfth year of my age,
I became impressed with the idea that parents were accountable
for their children until they were twelve years old,
and that afterwards they stood answerable for their own conduct through life.
This rested on my mind as a thing not to be erased,
and the thought of becoming an accountable being was humbling to me.
I thought I had rather die before I attained to that age,
so as to be at peace with Him who was to judge me after death,
than to enter upon a state in which I must answer for my self.

"`My parents kept a ferry and a public house, and were in the way of having much company.
I had by this time become quite a little musician; for which I was somewhat admired,
which tended to lead my mind into folly.
On the other hand,
I was often brought into serious consideration respecting my own state,
insomuch that at times, when I have been called to play for the company,
I have hid myself, in order to avoid it;
while the secret thoughts and feelings of my heart have caused my tears to flow freely,
from the desire I felt to escape from these scenes of dissipation,
and my sorrow for mingling in them.
But I would wipe away my tears, and return to the diversion.

"`Although I then knew not what it was that thus reproved me,
I have since discovered that it was nothing short of Divine love
and mercy that thus disquieted my mind in the pursuit of vanity.
I mention these things for the good of other children,
to show how necessary it is for them not only to be sensible of, but to take heed to,
the tender visitations of Divine mercy and love.
A child trained in the way he should go,
is greatly benefited thereby--such reflections have been lasting in my memory.`"

[.small-break]
'''

It is to be regretted that the foregoing fragment
is all that can now be found of her own account,
but from information verbally communicated,
it is evident that after her mind became religiously engaged,
she endured much opposition and difficulty in her father`'s house,
in consequence of her faithfulness to what she believed to be the requiring of her Lord.
She had allowed herself to be drawn into a participation with the
vain amusements and festivities which were often practised,
had learned to play cards, and sometimes joined in the dance,
and being surrounded by those who had very little sense of religion,
and who approved and promoted these things,
her path was one of many trials and perplexities.
Her childhood, her musical voice and aptness with her instrument,
were subjects of admiration,
and served as attractions to company of a very light and unprofitable character;
and as the resort of these to the house was a source of pecuniary profit,
her father was very reluctant that she should give up her singing and playing.
But her convictions of the sinful nature of those amusements grew stronger,
and her consequent distress of mind increased until she
found she could have no comfort but in abandoning them.
Many and great were her struggles,
often secreting herself when she knew company was coming, and pouring out her tears,
with strong cries to the Lord for help and deliverance,
and at length her obedience was crowned with success,
and they ceased to look to her for the entertainment of visitors.
She burnt her pack of cards, to the use of which she had been addicted,
ceased to sing and to play on her musical instrument,
and sought to lead a life of piety and self-denial.

Her faithfulness in these requisitions was followed
by increased spiritual light and strength;
her deportment became more serious and solid, and though much exposed to rough company,
both in the tavern and at the ferry,
where she often assisted in conveying passengers across the stream,
yet her heavenly Father graciously watched over her for good,
and preserved her in a line of conduct which was free from reproach.
Her schooling was much neglected, and her literary acquirements were very slender.
But the seasoning virtue of Divine grace, and an humble obedience to its teachings,
were eminently instrumental in raising her up out
of her low estate and making way for her,
and, as a wall of defence on the right hand and the left, protected her from harm.

For a time she went occasionally among the Baptists;
but as she grew in religious experience, her mind was drawn towards Friends,
with desires to attend their meetings for Divine worship:
but she met with many difficulties and discouragements,
and at times was much cast down and almost ready to give out.
On one occasion,
when two Friends from England had appointed a meeting near where she lived,
her desire to attend it was so strong that she determined
to break through the crowd of hindrances,
and go.
But she was poor, and her scanty wardrobe did not furnish apparel,
which those about her deemed suitable for her to appear in, and, having no bonnet,
they urged that her appearance at the meeting would not be reputable.

After the others had gone,
and sufficient time had elapsed for them to reach the meeting-place,
she resolutely set out on foot in her homely attire,
and with great exertion reached the meeting soon after it was settled,
and softly entering, seated herself near the door where she was much out of sight.
Divine goodness condescended to over shadow the assembly with his living presence,
and the Friends, +++[+++believed to be Deborah Darby and Rebecca Young]
were led to minister to her state in a powerful and encouraging manner.
She was deeply affected and confirmed in her convictions of duty,
and strengthened to pursue the path, which the Lord had cast up for her to walk in.

Having married, and removed with her husband to Pilesgrove, in Salem County, New Jersey,
she believed it her duty to apply for member ship in the Society of Friends,
and her conduct being consistent and exemplary,
she and her husband were received as members by that Monthly Meeting.
She passed through many fiery baptisms and deeply trying exercises,
during which the enemy of her soul was let loose to buffet and tempt her to such a degree,
that hope of deliverance from his power seemed to be wholly veiled from her view,
and the dark waters of despair ready to overwhelm her disconsolate spirit.
Day and night was she beset with the temptation to do violence to herself,
and as often as opportunity presented for accomplishing it,
some unexpected circumstance would providentially occur to frustrate her designs;
and at length the compassionate Saviour, who was in mercy watching over her for good,
and whose preserving power had marvellously kept her,
was graciously pleased to rebuke the evil one,
and deliver her soul from the thraldom in which it had been held,
giving her to taste of his mercy and goodness, and to feel the sweet incomes of his love.

This blessed transition from the pit of despondency to the light of God`'s salvation,
so filled her soul with humble gratitude and joy,
that she was ready to break forth in songs of praise,
and like the poor woman in the gospel, feeling that she had been forgiven much,
she loved much; and a remarkable trait in her Christian character through her after-life,
was love to her Saviour, and in her ministry,
the exaltation of his blessed Name and his divinity
and offices in the work of man`'s salvation.

Continuing obedient to the manifestations of the Lord`'s will,
and learning in the school of Christ the things that pertain to salvation,
it pleased the Head of the church to confer upon her a gift in the ministry of the gospel,
and to call her to declare unto others what had been done for her soul.
Sensible of her own weakness and her want of education,
and having a very humble opinion of her religious attainments, she shrank from this duty,
and was brought under great conflict and into many reasonings.
She pleaded earnestly to be excused,
and omitting to give up in simplicity when the requisition was clearly made known,
her difficulties increased,
and she was ready to conclude she could never publicly speak in the Lord`'s name.
She reasoned that there were many others in every way better qualified
than she was--that she was among the poor of this world,
and very illiterate, and therefore not likely to be acceptable to some,
and that surely she might be excused from this humiliating sacrifice.

While these struggles were going on in her mind,
she went one day into the village of Woodstown, with her husband,
and was sitting alone in the carriage at a store-door,
when a man looked into the front of the carriage, saying,
"`I do not know what thy name is; but I must speak a little to thee.
The Master has a work for thee to do, if thou art faithful to it.
I want to tell thee not to plead as Gideon did, '`My family is poor in Manasseh,
and I am the least in my father`'s house.`' This was Gideon`'s excuse;
don`'t let it be thine.
I want thee to be faithful--be obedient.`"

This unexpected salutation from an entire stranger,
one who could not know her secret plunges and discouragements, had an animating effect,
and quickened her diligence.
The individual, who thus unexpectedly spoke so suitably to her case,
was that worthy minister, the late Arthur Howell, of Philadelphia,
who had been attending the Quarterly Meeting of Salem.
About this time, she had a remarkable dream, which she thus relates:

[.small-break]
'''

"`I thought I was travelling on a road, and saw something at a distance, which,
when I came up to it, I believed to be Death.
I was glad to see him, as much so as two intimate friends are to see each other.
He asked me if I was ready to go with him.
I answered, "`O yes, I am ready;
and willingly will I go with thee.`' At the same time I thought a sense
was given me of the sweet peace and happiness enjoyed by the righteous,
when the appointed Judge of the world, the Son of God,
gives them a peaceful admittance into the presence of his Father and the holy angels.
I was anxious to be gone; and Death asked me again if I was ready, and I said, Yes.
He then looked earnestly upon me, and while he thus looked,
it seemed as if I was weighed in the balance and was found lacking.
My feelings began to change.
As a look from the Lord Jesus reminded Peter that he had denied that he knew Him,
his Lord and Master, and he went out and wept bitterly,
so did this look of Death remind me, with solemn conviction,
that I could not then go with him in peace.

"`I began again to talk with him, and, in much fear and sorrow, said, '`O Death!
I thought I was ready to go with thee, but I find I am not.
There is only one thing that doth hinder me, and I will tell it to thee.
I am a monument of Divine mercy.
I have known both the terrors and the lovingkindness of the Lord,
and having experienced his mercy and the sweet power
of Jesus to deliver and save alive the soul,
the Lord has required of me to make an acknowledgment of it to the world,
and this I have not done.
Had I done this, had I not been disobedient in this duty, I should be ready to die.
But, O spare me a little longer.
Tomorrow will be Fifth day.
I will go to meeting,
and there make a public confession to the goodness of the Lord through his dear Son,
and after this thou mayst come, and willingly will I go.`' I thought he agreed to this,
and when he turned away from me, I looked after him as my real friend, and grieved,
saying, '`O what can all this world do for me!
Soon should I have been in a state of happiness,
out of the reach of sin and sorrow,`' and while thus mourning over myself.
I awoke.

"`The following day was the Fifth-day of the week, and I went to meeting.
A solemn and weighty season it was to me,
and the sense of my own unworthiness was so great that I sat under the load of the cross;
and returned from the meeting unfaithful still to my promise.
I was then made sensible that it is possible to grieve the Spirit of Christ,
and felt deep conviction; and the same power that brings terror upon the guilty soul,
did not speak peace to me, in my long and repeated strivings against his will,
in which I was pleading, '`Lord! send by whom thou wilt send, only have me excused.`'

"`After this act of disobedience, I fell into great distress of mind,
and could take no interest or comfort in the things of this world,
concluding I was a lost sinner, unworthy of the notice of our Redeemer and Saviour.
Never will my anguish be erased from my remembrance.
In my retired walks, when no one could see me, in the depths of my grief,
were my petitions made that the Lord would grant me some
evidence of pity and pardon from his throne of mercy,
and not cast me off forever.
Thus I mourned for the presence of my Helper and Redeemer;
during which time I was taken sick, and after several days passed in deep exercise,
which I kept hid in the secret of my own heart,
I was favored with comfort and consolation,
and a sweet evidence of my acceptance with Jesus Christ our Lord and Saviour.

"`I was raised from this sickness, and not long after,
I gave up to make a public acknowledgment, in our meeting, to the goodness of the Lord,
in that He had taken me as a brand from the burning, unworthy as I was,
and had shown mercy unto me.
And oh! unspeakable were the joy and comfort which I felt.
As I walked along the road in returning home, the fields and whatever I looked upon,
seemed like a new creation, and I rejoiced that I had suffered for the Lord`'s name.
I hardly believed that I should ever suffer and grieve any more as I had done,
nor did I then expect that it would be my duty again to speak in public of his goodness,
or to tell unto others that the Lord is good,
of long suffering and tender mercy to poor sinners that they may return,
repent and live.`"

[.small-break]
'''

Her first appearance in the ministry was about 1803 or 1804,
and the thirty-second year of her age.
In 1806, her husband removed into the compass of Haddonfield Meeting,
by which she was acknowledged as a minister in Fourth month, 1807.
She returned with her husband and children to Woodstown, in 1811.
In the same year, she obtained certificates from the Monthly and Quarterly Meeting,
expressive of the unity of Friends with her prospect of making
a religious visit to the meetings in the Genessee settlement,
State of New York, and in Upper Canada; but after some time,
apprehending the will was taken for the deed,
and that her divine Master released her from the service,
she returned the certificates to the Monthly Meeting, without proceeding in the visit.

The following paper is dated about six months prior to the
declaration of war by our government against Great Britain;
a contest which, during the period between 1812 and 1815,
brought so much trouble and distress upon the United States,
and caused great loss both of life and property:

[.embedded-content-document.paper]
--

My soul is impressed with a sense of duty to God, which I dare not decline,
and with no other motive but to discharge it, and to relieve my own mind,
do I write these lines, with earnest desires for the good of mankind and of my own soul,
and that grace, mercy, and peace may be multiplied unto us.
On the 10th of Twelfth month, 1811,
at a time when this world and all things therein were little
in my view in comparison of the love of God,
and of rest in heaven; as I lay upon my bed, a deeply solemn feeling came over my mind,
and in the light of the divine Spirit and power,
there was opened to my view a very dark curtain or cloud,
which seemed to me to portend great sorrow and calamity hanging over the land.
As I beheld it, my feelings were indescribable, for it was accompanied by a voice,
which repeatedly uttered words, '`The sword, etc.,`' that threatened awful judgments,
because of the sin and iniquity which abound in the land.

The appearance and weight of these things filled my heart with awe,
and I was made to weep and tremble before the Lord: but I had also to adore his Name,
under a fresh sense given me of his mercy and compassionate
regard being yet offered to us.
Our Saviour would once have gathered Jerusalem, the place He chose to put his name in;
and from the sensations given me,
I was led to believe that the outstretched arm of God`'s mercy was yet
disposed to gather our nation into the love of his dear Son,
if they would hear and obey Him.
This sense of Divine love and goodness still, offered to our country,
was accompanied with lamentation and mourning because of the present state of the people,
and so heavily did this rest upon me for several days,
that I entreated the exercise and sorrow might be taken from me.
For I said in my heart, O Lord,
can it be thy blessed will to exercise my mind in this wise,
seeing that I am poor and unworthy; I am but a weak female,
far from taking any notice of public concerns; yet I dared not say to the Almighty One,
what doest thou?
And now, what rests with me to deliver is, that the Lord is calling loudly to all,
and especially to those in authority, in these United States,
to hear and obey the voice of his beloved Son,
whom in great love He hath given for a crown of glory, and for a diadem of beauty,
and for a spirit of judgment to those who sit in judgment; of whom it is said,
"`Let all the angels of God worship Him.`"
The eye of the Lord runneth to and fro in the earth, beholding the evil and the good,
and He has a controversy with this people for sin and for iniquity,
even with the inhabitants of this favored land,
whom He hath known of all the families of the earth,
because they have too generally forgotten the God of their salvation,
and not been enough mindful of the Rock of our strength.
Therefore, saith the Most High, how art thou changed?
How is thy gold become dim?
The nations of the earth have heard thy shame, and the cry thereof hath filled the land;
for the mighty men have stumbled and fallen against the mighty.

[.signed-section-signature]
Rebecca Hubbs.

--

In 1813,
she was liberated to perform a religious visit to some of
the meetings in Baltimore and Virginia Yearly Meetings,
and in the State of Ohio, and to appoint some meetings among those not of our Society.

For a considerable time previous to obtaining certificates for this service,
her mind had been exercised with an apprehension that it was required
of her to make a visit to the President of the United States.
Reasoning upon her own unfitness for such a mission, she became discouraged,
and concluded she could never yield to, or perform it,
and strove entirely to put it away.
But she could not in this way obtain relief from the concern,
and then thought perhaps her burdened mind would be relieved by writing,
and she penned an address to the rulers of the United States,
expressive of what seemed the exercise of her spirit.
But she found that no sacrifice of her choosing would
be accepted as a substitute for the Divine requisition,
and about the time she wrote it,
the Meeting for Sufferings in Philadelphia issued an address
to the rulers and people of the United States,
in which the substance of what she had penned was embraced.
This she hoped might entirely release her;
while she was strengthened by the concurrence of her concern with
that which had engaged the attention of a body whom she highly
valued for the religious weight and experience of its members.

[.offset]
Writing on this subject, she says:

"`I long went bowed down in mind, pleading in the secret of my heart, '`O holy Father,
may this burden and distress of mind pass from me,
for how can I believe it to be thy blessed will thus to exercise my mind,
seeing I am a poor, weak, unworthy woman,
and far from taking any notice of public concerns.`' About this time I was taken sick,
but my distress of mind was harder to bear than my bodily sickness;
I found there was no one could relieve me of the exercise, which still remained with me.
After my recovery I passed along in secret pain for a few months,
when I obtained a certificate to pay a religious visit to
Friends in some parts of Virginia and other places,
and my dear friend, Sarah Scull, gave up to accompany me,
but what was to me the most weighty part of the concern lay concealed in my own bosom.

"`We left home, and, crossing the Delaware river, went to Wilmington,
and attended meeting the next day.
At the Friend`'s house where we dined,
they showed us a picture of the President`'s mansion,
but my feelings were such that one look was enough, and I turned quickly away.
Soon after this I dreamed that one of the greatest officers in
the American army came to me with a drawn sword in his hand.
I stood before him trembling with fear, expecting to be pierced through;
and just as his weapon was raised against me, I put forth my hand, and touched it,
when it became flexible, and rolled up like a piece of ribbon.
Dear Sarah Scull awoke me,
and desired I would tell her what it was that so troubled my mind; and,
on my informing her, she entered feelingly into sympathy with me,
and said she would go with me to the President, and do what she could for me.
From this time a sense of the importance of the service filled my heart,
and the fear of the Lord reigned over all other fear; my fervent prayer was,
may the words of my mouth, and the meditations of my heart be acceptable unto thee,
O Lord, my strength and my Redeemer.
After visiting some of the meetings in Virginia, way was made,
through the kindness of our Friend, Micajah Crew, of Cedar Creek meeting in that State,
to visit in person James Madison, then President of the United States.`"

[.small-break]
'''

The President [James Madison] and his wife received them very kindly,
and they had a solid and satisfactory religious opportunity with them,
in which they were much affected,
and they parted with many tokens of affectionate regard.
The President insisted on serving them with some refreshment,
and following them to the carriage,
placed in it some articles which he thought would be useful to them in their journey,
and after a renewed expression of the satisfaction the visit had given him,
he solidly took leave of them again, desiring a blessing might attend them.

In the spring of 1814,
her mind was impressed with a sense of religious duty to make a
visit to some of the meetings of Friends in the State of Ohio,
particularly within Miami and Salem Quarters, and having the concurrence of her friends,
as expressed in their certificates, she left home in the Seventh month of that year.
She entered on this engagement under much discouragement, it being a time of war,
and much unsettlement among the Indians on the frontiers,
near some of the places included in her prospect,
but she was enabled to cast her care on the Lord,
and to trust in that Arm which had hitherto been her support and help.

[.offset]
The following extracts from some memorandums made during the journey,
may be interesting to the reader, viz.:

"`Second-day morning.
Much bowed down in mind, having a perilous journey before me,
and a feeling sense of poverty and weakness,
under which I rode with a heavy heart through the streets of Philadelphia;
but after getting into the road that led to the westward,
I was much revived by a renewal of faith,
enabling me to believe that the great Shepherd had not forsaken me.

"`Seventh month, 19th. Attended a meeting at Fallowfield, appointed by Micajah Collins,
in which I was bowed in supplication,
under a particular exercise that the Lord would be pleased to strengthen
and preserve those who had left all to follow Him.

"`Fifth-day, 21st. Went on to meeting at Lampeter,
where we were favored to witness the owning of Truth to our comfort and satisfaction.
Micajah had much to communicate respecting Israel`'s
journey out of Egypt into the land of Canaan.
I, a poor little one,
had to cast a mite into the treasury for the encouragement of some present,
who felt as if they were wounded and half dead, through the weakness of the flesh,
and the reasonings of their soul`'s enemy.
Truth, I believe, reigned over all to the mutual comfort of the visitors and visited.
All blessing and praise be ascribed unto Him, who is forever worthy.`"

[.small-break]
'''

It is proper to notice here that Micajah Collins was also engaged in a religious visit,
embracing many of the meetings to which Rebecca`'s concern extended;
and he proposed that they should proceed in company.
Rebecca was cautious about embracing the proposal, and deferred giving an answer,
but after solidly weighing it for a day or two,
she thought it right to join him in visiting the meetings east of the Allegheny mountains,
and they accordingly went on together.

[.small-break]
'''

"`Second-day, 1st of eighth month.
Set out early on our journey, and passed through Chambersburg, Campbell`'s, and London,
and had a fair view of the lofty mountains, many of which were in sight,
and were far more pleasing to me than the nicest work of man`'s hand.
As my mind mused upon the prospect,
beholding these vast mountains looking upon each other in silent grandeur,
with the mighty rocks that seemed to peep through the lofty forests,
they appeared to me to be harmoniously sounding forth
the praise of Him that liveth forever,
and calling upon the passers by to adore that Arm that is all-powerful and divine.
My heart joined in the song of praise, and the language ran through my mind,
'`The mountains and the hills shall break forth before you into singing,
and all the trees of the field shall clap their hands,`' and as
we went on my heart was filled with adoration and praise.

"`Rode nearly forty miles over very bad roads, and was much worn.
I went to bed much bowed down in mind and greatly discouraged,
almost ready to conclude I could not go forward,
and the night was to me almost sleepless.
Towards morning slept some,
and awoke with the encouraging language passing through my mind,
--'`I will guide thy course through the deep waters,
and clear thy path over the high mountains.`' It was truly comfortable to me,
as an assurance of not being left by my gracious Master;
and whether I am permitted to return to my family or not, I venture to pen it,
and commit myself to Divine protection.

"`Fifth-day, 11th of eighth month.
Had a meeting at Westland, and soon after I took my seat,
the noise of strife seemed sounded in my mental ear, causing me close exercise.
But I had to endeavor to relieve my mind,
which I was helped to do from these words which were presented to me,
'`Why dost thou condemn thy brother, or why dost thou set at nought thy brother,
seeing that we must all stand before the judgment seat of Christ?`"
Micajah Collins afterwards took up the subject and had good service,
and I believe the meeting ended well.
After it was over, a Friend said to me, "`Some of us will have cause to remember thee.`'

"`First-day, the 14th. Attended Wheeling meeting, and soon after we sat down together,
my mind was filled with an exercise something similar to
that of Abraham when he was pleading for the city of Sodom:
Peradventure there may be found ten righteous there.
And the Almighty said, I will not destroy it for the ten`'s sake.
My feelings were awful,
and I had to labor in the ability afforded me that the people would join
together in endeavoring to support the standard of Truth and righteousness,
that when a time of searching came,
there might be found in the city righteous ones for
whose sakes the Lord would be pleased to spare it,
and their own souls be saved with an everlasting salvation.

"`Third-day, 16th. Came to St. Clairsville very much fatigued, and,
as I sat in the Friend`'s house where we put up, I said in my heart,
How glad should I be if I could enjoy the privilege of working in my own house,
lying down under my own roof and in my own bed,
without looking out for new quarters every night.
But I am a stranger in a strange land, and as a poor pilgrim in this world.
Then the prayer arose in my soul, O my dear Redeemer,
for whose sake I have been made willing to leave all and
to bear all that may be permitted to come upon me,
suffer me not, I pray thee, to murmur or repine,
but grant me ability to perform all thy will.

"`Fifth-day, 18th. Attended Short Creek meeting where was a large gathering,
and feeling an impression to bow in reverence and supplicate the Divine Goodness,
such an awfulness covered my spirit that I thought I should have fainted upon my seat,
if I had not given up the requiring.
Just as I did so, a large post in the house fell and hurt a woman very much,
but the solidity of the meeting was preserved to admiration.
Micajah Collins had good service afterwards, and the meeting ended well.
After it was over,
I was told by several Friends it was cause of thankfulness
that the people were on their feet at the time,
or much more injury would probably have been done, and the woman who was hurt,
said that if she had not been standing up, she thought she should have been killed.
Marvellous it was that no one was killed or hurt worse,
for which mercy I was truly thankful.

"`First-day,
21st. There not being room in the meetinghouse to
hold all the people who came at Yearly Meeting time,
a shed was erected at the men`'s end,
and meetings for worship were held there and in the house.
On setting off to walk to the meeting,
I felt myself as one of the least in my Father`'s house,
and many Friends being at our lodging, I was willing to keep back out of sight.
Feeling a draught in my mind so to do, I turned into the shed.
There was a great collection of people, and I felt cautious of speaking,
lest I might stand in the way of some brother or sister.
I thought there appeared to be a hunger and thirst after righteousness among the people;
and though my heart was filled with a sense of my own weakness,
it flowed with love to the assembly, and under a feeling sense of Divine goodness,
and the Lord`'s love and compassion to all mankind universally,
I stood up and witnessed renewed strength and help to be afforded in the needful time,
whereby I was enabled to relieve my mind.
The great Head of the church was pleased to own the assembly with his living presence,
to the refreshing of many minds,
and the tribute of praise and thanksgiving was offered
up from many hearts to Him who is forever worthy.

"`Third-day, 3rd of eighth month.
Attended Stillwater meeting where was also our friend, Charity Cook.
The case of Zaccheus, the publican, came before my mind, and ability being afforded,
I labored to encourage all who felt themselves little and low to come unto Christ
just as they are--for our dear Saviour condescended to be the guest of Zaccheus,
and his visit had a glorious and blessed effect.
When he received him, He said,
'`This day is salvation come to this house;`' and
though accounted a sinner and despised by some,
yet Jesus owned him for a son of Abraham.
Feeling my mind oppressed with a dividing spirit
that would exalt itself above a brother or sister,
I travailed under the exercise,
and was at length enabled to labor for the recovery of such,
and the restoration of love and unity;
that love to God and to one another might reign over all among them,
and every obstruction to the arising of Divine life be removed.
The canopy of Divine love was mercifully spread over us,
for which favor I desire ever to be thankful, for it is not at the command of mortals,
but from our heavenly Father,
who only is worthy to receive thanksgiving and high renown forever more.
Just as the meeting broke up, a burial company came into the graveyard,
and I accompanied the mourners to the grave-side,
where I had to hold out an invitation to the company to know Christ formed in them,
and his kingdom exalted there, by the power of his Spirit,
that so we might be prepared for a glorious and happy resurrection.

"`Ninth month, 2nd. While travelling on the road about the middle of the afternoon,
a covering of awfulness spread over my mind,
and I was brought near to the Lord in secret prayer,
that He would be pleased to support me in what ever I might
have to pass through for his name and cause`' sake,
and the peace of my own mind.
I believed from the impressions on my mind, that some service was near,
but knew not what it could be,
as we had many miles to travel before we could get to a Friends`' meeting.
We stopped at New Lancaster to stay all night, and having a pain in my head,
and being much fatigued, I laid myself down for a little rest.
On rising, I saw nearly opposite the tavern a camp of soldiers,
and found that the exercise which had been weighing upon my spirit,
was for a meeting with these soldiers.
My concern increased so that I found I dare not omit making the effort,
and accordingly gave up to it.
I requested the men Friends who were with us to mention it to the tavern-keeper,
and for some of them to go to the head officer,
and inquire if he was willing his men should receive a visit from us next morning.
Although I thought it my duty to make the effort, yet, as it was their review day,
I concluded it would be in vain to expect to see them together in any stillness,
as it was a time of so much noise and excitement,
and they were preparing to go out to battle.
On the return of the men Friends,
they said they had seen the commanding officer on the subject, and he was very willing,
and proposed that we should meet next morning in the courthouse.

"`On Seventh-day morning, near the time appointed,
the officer came to the inn and asked if we had a choice in having the townspeople invited;
for if we had, by ringing the courthouse bell, they would soon collect.
I told him I had no desire to see any but the soldiers and officers,
and such as he might choose to sit with him.
He accompanied us to the courthouse, and then went to bring his troops,
and pretty soon returned with them.
Several officers came with the soldiers, and many of the townspeople,
the meeting being made up of high and low, rich and poor, the lame and the blind.
I may say with truth that they behaved with much solidity,
and though on my first sitting down I felt so poor,
and under such a sense of my own weakness, that I said in my heart, why am I thus left,
and was ready to query whether I had ever known any good,
yet blessed be the name of Israel`'s God He was pleased to grant a spring of Divine life,
and to manifest his tender compassion and the redeeming love of his dear Son,
and sent comfort into some poor souls.
He was pleased to own the meeting with his living
presence to the humbling and tendering of many,
in particular, some of the poor soldiers,
as well as some of the officers in their shining apparel.
It was affecting to see their tenderness.
I was drawn forth in supplication for their preservation, and for the good of all present.
After the meeting was over and we were leaving the courthouse,
the commanding officer came up to me, saying, "`I bid you good-bye, madam,
and indeed I am very much obliged to you`'--but his countenance bespoke more than words,
and I thought he was designed for better things.
All blessing and praise be given to the Most High,
in that He is pleased to appear for the help of his poor creatures,
when all things seem shut up--the heart cold and barren--when the heavens seem as brass,
and the earth as iron.
Oh, then is He at times pleased to take away the stony heart,
and to give hearts of flesh, and send comfort into the soul by his quickening spirit,
whereby the valleys are raised, the lofty mountains brought low,
the rough places made plain,
and the crooked paths straight--for the coming of the kingdom of heaven.

"`We left New Lancaster feeling the reward of sweet peace,
and some tears of rejoicing fell from my eyes as I rode on my way,
in contemplating the many favors and mercies I have
received from the bountiful hand of Israel`'s God.

"`6th of Ninth month.
Attended Walnut Creek meeting, where I had much labor with, and deep feeling for,
a tried and tempted state.
After the meeting a woman took an opportunity to open her mind to me,
and said she knew not what was to become of her; she was so tempted,
and something seemed to be always following her,
trying to induce her to take her own life, It was very distressing to my feelings;
but I gave her the best advice that was afforded me at the time,
and in my heart committed her to the great Caretaker, even Jesus of Nazareth,
the Physician of value.

"`8th. Went to Lee`'s Creek meeting in company with Mildred Ratcliff.
When I first sat down I thought nothing could be done here, nor any good witnessed,
for the noise of the little children.
I counted thirteen small children dandling upon the lap, and two walking about the floor.
But He who can still the waves, even of the troubled Ocean,
was pleased to give us a time of stillness,
and we had a favored meeting and thought ourselves amply repaid for coming here.

"`9th. Rode between twenty and thirty miles over a very rough road,
and being much fatigued, and in a wilderness country,
I came very near repining at my lot, and said that which I ought not to have said,
like murmuring at the hardships and fatigues I endured.
Alas! it was presumptuous, and I suffered very much for it in the night,
but after heartfelt repentance I found forgiveness;
yet for these few words I suffered more than I remember to have done in a long time,
either for word or deed.`"

[.small-break]
'''

They now came into a part of the country where a
disease called the cold plague was prevailing,
and at some places so many of the families were sick,
that they found it difficult to procure entertainment;
the disease being considered infectious, and in many cases very malignant and mortal;
her companions apprehended danger from exposure to it, were very much afraid of it,
and reluctantly went where it was known to be.
This brought her into a great strait, and plunged her mind into much discouragement.
She felt tenderly for them,
and while her faith was strong that they should be preserved from
the pestilence so long as they were in the path of duty,
she could but feel deeply the responsibility of taking them into the way of danger.
Painful were her conflicts,
and earnest her cries to the Lord for right direction
and for entire resignation to his will;
and after a season of much mental suffering,
she was confirmed in the persuasion that it was her duty to go on with her religious
visit as it had first been unfolded to her in the Divine light,
leaving all else to the ordering of her gracious Preserver.
In communicating this conclusion to her companions,
she left them entirely at liberty either to go with her or not,
as should feel most comfortable to themselves.
They did not feel willing to leave her, and accordingly proceeded on their journey,
committing themselves to the protecting care of Him
in whose hand are the issues from death.
She writes under date of Ninth month 13th.

[.small-break]
'''

"`Passed through Urbanna, and came to the house of P. H.,
who honestly told us his house was full already, and they had several sick.
On asking him where we could go, he said there was a house about a mile further on;
but if we thought we could make out with the accommodation he could give us,
we were very welcome.
Being very weary with travelling, we turned in with them,
and as we were going into the house,
my female companion asked me if I did think it was
required of us to go where things were in this way.
When I sat down by the fireside, my body ached with fatigue,
and my heart with discouragement,
yet on reflection I felt satisfied in my mind that
it was in obedience to the Lord`'s will I had come.
Next day went to their meeting,
and although it was small by reason of the sickness in the neighborhood,
yet it was satisfactory.

"`18th. Attended Derby Creek meeting, where I experienced much close labor and exercise,
but at length was set free and felt clear.

"`19th. Was at Mad River meeting,
where my soul sang praises to the Lord for the many favors and mercies I have received,
and for his redeeming love universally extended to all man kind.
Next day we crossed the Mad River,
and bade farewell to Friends and others of these settlements,
with that enriching peace of mind which amply rewarded us
for all our toil in making this visit on the frontiers.
Some of the places we have been at were within five or six miles of the Indian line,
and Friends have several times been alarmed by the visits of the hostile natives;
but when they found Friends had no guns, and would not fight,
they went away without doing them any hurt.

"`In passing again through Urbanna, we saw the horsemen gathering there,
fifteen hundred of them being to assemble here previous to going out to battle.
At our next lodging-place, I said in my heart, surely this is a waste howling wilderness,
for we could hear the barking of the wolves around us, as we sat in the house,
and there was sickness in the family, so that we were much discouraged,
and I repeated to myself Cowper`'s touching lines:

[verse]
____
"`When I think of my own native land,
In a moment I seem to be there,
But, alas! recollection at hand
Soon hurries me back to despair.

There is mercy in every place,
And mercy--encouraging thought--
Gives even affliction a grace,
And reconciles man to his lot.`"
____

"`Although the scene around us seemed gloomy in one sense,
the inhabitants enclosed by the wilderness which makes the place seem solitary,
and the howling of the wild beasts is heard in their dwellings,
and the pestilence now passing up and down among them,
while in the towns there is the noise of warriors preparing for battle,
and the hostile Indians near their borders,
yet even here is a place of repose for the mind when centred on the Lord,
and in sweet meditation I felt a joy and divine harmony,
and living praises to Israel`'s God, while a lively spring of faith arose,
whereby I was enabled to put my trust in the Lord.

"`22nd. Was at Embree`'s meeting.
It rained very hard,
but we were favored to witness the living presence of Him whom we seek,
and a woman of another religious society, who was there,
said she would be willing to go every day through the mud
and rain for the sake of being at such a meeting.

"`23rd. Attended Cesar`'s Creek meeting, where much exercise was felt and labor bestowed,
and it appeared as if the battle went on the King`'s side,
until there was not a foe left.
After meeting, went to the house of our friend, Charity Cook,
with whom and her husband and children we had an agreeable time.

"`26th. Was at the meeting at Waynesville, which was large and satisfactory;
favored with the cementing love of God which reigned over death and darkness.

"`Sixth-day, 7th of Tenth month.
Went to Centre meeting, which was large, and, I was told by others, satisfactory.
When I first took my seat, I was deeply sensible of weakness and poverty,
but soon was brought under exercise and into public labor,
having to stand up with but a very small spring of Divine life, but, as I went on,
witnessed an increase of strength and life, to the relief and peace of my own mind.

"`14th of Tenth month.
Having attended the last meeting that I had a prospect of visiting in these parts,
I was made thankful in having a sweet evidence given me that my
labors were accepted by Him who regardeth the little ones;
and taking leave of the Friends who accompanied us,
with an appearance of heartfelt affection, we set out for Chillicothe.

"`First-day, 16th of Tenth month.
It appeared right for us to have a public meeting at Chillicothe,
which was accordingly held in the afternoon in the courthouse.
The Presbyterians and Methodists showed us much kindness,
and not only gave out word of our intention in their meetings,
but broke theirs up earlier in order to make way for ours,
which was attended by a large company of people.
I was told that seven hundred and sixty-seven persons were counted,
who came out of the house, beside many that stood around the door,
and there were only two besides ourselves who made any appearance of Friends.
We were treated with kindness by those from whom we should hardly have looked for it;
even by the war party.
General McA`'s wife came and took dinner with us, walked with us to meeting,
and sat in it by my side.
Many military officers, in their shining uniforms, were present,
and sat with solid countenances,
and I could but adore the universal love and mercy of God to all souls,
who graciously makes himself known in the hearts of all,
though many come short in obedience.`"

[.small-break]
'''

After this meeting, in consequence of a pressing invitation,
they went to the house of a General, then absent from home, in the American army.
His wife had been at the meeting,
and was much tendered under the testimony of Rebecca Hubbs.
In the course of the visit she manifested great anxiety on account of her husband,
word having been received from him that the army was expecting a battle about that time,
and she was much distressed lest her husband should be killed himself,
or be instrumental in shedding the blood of others.
To add to her affliction her only son had recently been drafted for the army;
and she was in daily expectation that he would receive marching orders.
Rebecca seemed to be brought into much sympathy with this distressed woman,
and before they left the house, sought and obtained a religious opportunity,
in which she had to assure her that her husband would not be in the expected battle,
but that his troops would be disbanded, and he return shortly to her in safety;
and that as regarded her son, he would not leave her,
for that the drafted men would not be called out.
Deeply impressed with Rebecca`'s religious communications
both at the meeting and in her own house,
these prophetic declarations found a ready response in the
mind of the General`'s wife and they left her in tears,
greatly comforted and strengthened by the visit.

It was a very common circumstance for Rebecca Hubbs to give way to discouraging reasonings,
after having been helped through a meeting or other religious engagement,
and on the present occasion she suffered more than usual from this cause.
The uncommon character of her communication in this instance
furnished a fruitful source for arousing her fears,
and although at the time she had believed herself rightly authorized to say what she did,
yet she soon began to call all in question.
The prospect of the meeting at Chillicothe had been very exercising,
and her fears respecting it many and strong;
and her prayers for Divine help to get through it
to the honor of her Master and the good of the people,
had been, as she believed, mercifully heard and answered.
The General`'s wife, as well as many others, had been much affected and tendered,
and now she thought if,
after having been thus graciously cared for and owned by Him whom she desired to serve,
she had presumptuously uttered what was not given her, and it should not be fulfilled,
the tender-spirited woman might be stumbled and induced to doubt her commission,
and thus a shade be brought over the Truth.
Considerations of this kind marred the peace she felt after the meeting,
and though at times enabled to rise above them,
and in the retrospect of her labors to feel the precious answer
of "`Well done,`" yet she frequently thought during the homeward
journey that if she could only know that her words had been fulfilled,
her cup of rejoicing would be full.

About two months after reaching home, and returning her certificate,
she received a letter from the General`'s wife, in which she said,
"`every word you told me at my house has been fulfilled.
My husband was not in any engagement; his troops were discharged,
and he returned home in safety, and my son did not go into the army,
the drafted men not being called out.`"
This intelligence bowed her spirit in humble gratitude to Him, who,
when He puts forth his sheep, goes before them; and she could say in truth,
good is the Lord, and greatly to be praised.

From Chillicothe they turned their faces home ward,
and on the 1st of eleventh month were at Marlborough meeting in Ohio,
of which she remarks:

[.small-break]
'''

"`I felt much exercise of mind in this meeting,
that Friends might be clothed with the meek, humble spirit of Jesus,
whose love to the returning repenting sinner is so great that He
said there is more joy in heaven over one sinner that repenteth
than over ninety and nine just persons that need no repentance.
My mind obtained relief from its exercise,
and although I felt cold and barren on first sitting down in the meeting,
yet I believed it was a favored season and ended well.`"

[.small-break]
'''

In the evening she had a religious opportunity at a Friend`'s house,
where a number of young people were collected, of which she says:

[.small-break]
'''

"`In looking over the dear young people present,
I had to recur to the many days I had spent in vanity during my youth,
notwithstanding the early visitations of Divine love to my soul,
so that yet at times I feel abashed when I consider that,
for want of yielding obedience in my youthful days,
I fall so far short of what I might have been; and my mind being religiously impressed,
I had to exhort the youth to give up in unreserved obedience;
and afterwards the Friend`'s wife expressed her desire that the young
people present might remember the testimony which was left with them.

"`From this house there rode with us on horseback, to the next meeting,
twelve or thirteen Friends.
Soon after I took my seat in the meetinghouse my
mind was arrested as with the noise of strife,
and these words revived and rested with me, '`Where no wood is, there the fire goeth out,
so where there is no tale-bearer,
the strife ceaseth.`' The feelings attending my mind were very trying,
but I could not get from under the exercise, without laboring for love and unity,
and that the spirit of contention might be overcome, seeing we are bound to forgive
one another on the penalty of not being forgiven by our heavenly Father;
and our dear Saviour said, "`If thou bring thy gift to the altar,
and there rememberest that thy brother hath aught against thee,
leave there thy gift before the altar, and go thy way;
first be reconciled to thy brother, and then come and offer thy gift.`"
After supplication to the Lord, the meeting ended, I believe, to good satisfaction.

"`First-day, the 6th. Attended Salem meeting,
and admired to see so many people where lately it was all a wilderness.
In this meeting much exercise and labor fell to my lot,
for promoting attention and obedience to the Divine
principle of light and truth in the hearts of all,
and I felt my mind clear of the meeting.

"`After attending meeting at Beaver, in Pennsylvania, we rode to the house of J. W.,
in Allegheny County, whose only daughter has lately changed from a gay,
fashionable girl to be a religious member of the Society of Friends.
It is matter of joy to me,
whenever I behold among the dear youth any who appear engaged to
promote the dignified cause of God and the gospel of his dear Son;
and as the cross is great, so doubtless will their crown be also.

"`Left Pittsburg, and passing through Youngstown, crossed Chesnut Ridge,
and put up at a tavern, where they informed us a great company of soldiers had lodged.
It is distressing to my feelings to consider the sorrowful effects of war.
The destruction of property is great,
but not to be compared with the dreadful loss of life.
When I contemplate the tenderness and care of parents over their innocent children,
and think how many whom the protecting arm of Divine
goodness has enabled them to raise to manhood,
fall victims to cruel wars, which proceed from the lusts and envyings of wicked men,
their ambition and avarice, how mournful is it;
and alas! what is still more awful to contemplate,
is the case of the poor soul that is thus hurried out of time on the field of battle.`"

[.small-break]
'''

Writing of their journey across the mountains,
she remarks on the difficulty they had in procuring food for themselves and horses,
in consequence of a company of soldiers having marched
from Pittsburg for Baltimore a few days before,
and being but a little way before them,
had consumed all the food that could readily be obtained.

[.small-break]
'''

"`About one o`'clock we came to a large brick house,
where we stopped and endeavored to get some breakfast,
but were refused on our first application.
I sat in the wagon and heard my companion interceding for something to eat,
and telling the landlord that we had had but one meal`'s victuals for two days past,
during which we had been steadily travelling in the cold,
there being ice and snow on the mountains;
but the landlord said the soldiers had eaten all up.
I got out of the wagon, and, walking towards the door,
asked the landlord if we could not have some refreshment.
'`Why, madam,`' said he, '`the whole army lay here last night, and we have nothing left;
you know it is war time, and war makes hard times.`' I told him.
I knew it did, and that the very mercies of war are cruel.
There was an officer standing by, a stranger, who heard our conversation,
and seemed to pity us, and said, '`Walk in, madam;
you shall not go away without your breakfast.`' Then, turning to the landlord, he said,
'`Give them their breakfasts; you can do it well enough.`' We went in,
but the women said they were so fatigued they were hardly able to do anything;
yet would try, and they did give us an excellent meal.

"`Seventh-day, 26th. Resumed our journey early,
and passed through Stoystown before the volunteers were ready to march,
and now being foremost, we could get our meals in season.

"`Third-day, 6th of Twelfth month.
Went to Sadsbury meeting,
where I was much exercised on the subject of the Pharisee
and the publican going up to the temple to pray.
Many living desires were felt for the spiritual welfare of the assembly,
and I joined in offering up the tribute of praise
and thanksgiving to Him who is worthy forevermore.`"

[.small-break]
'''

From this place they proceeded home, where she was favored to arrive in peace and safety,
enjoying a precious reward for her dedication and faithfulness
under circumstances of peculiar difficulty and discouragement;
in all which the merciful support and protecting care of her heavenly
Father had been conspicuously manifest to her humble admiration.

In the First month, 1815,
she returned the certificate granted to her by the Monthly Meeting,
and produced minutes from Ohio Yearly Meeting, and some of its branches,
informing that her gospel labors among Friends there had been acceptable and edifying.

In the eleventh month of the same year, she obtained a minute from her Monthly Meeting,
expressive of unity with her concern to pay a religious visit to Friends
within the limits of Burlington and Haddonfield Quarterly Meetings,
New Jersey; which service she was favored to accomplish to her own peace,
and returned the minute in the First month, 1816.

About this time she received a letter from a military officer, high in command,
whom she had met with at Chillicothe, Ohio,
and for whose religious welfare she had felt much concerned.
It is as follows, viz.:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Chillicothe, January 6th, 1816.

[.salutation]
Respected Friend,

You will no doubt be surprised when you receive this letter;
but when you learn the circumstances that give rise to it, you will not, I hope,
consider it an unwarrantable liberty that I have taken.
Sometime in the fall of 1814, while on a tour through the State of Ohio,
you visited this town, at which time I was boarding at B. H. `'s,
where I saw and became partially acquainted with you.

At that time I had the honor of bearing a commission in the army of the United States,
and was preparing to march for Detroit.
It was at this time that you seemed to manifest a friendly interest in me,
and were kind enough to aid your manifestation of it, by your good counsel,
for which my grateful bosom now beats with gratitude sincere.
This is the reason why I write,
and I again entreat you not to consider this as an intrusion,
but rather as the effusion of a grateful heart,
ever thankful for advice or counsel coming from any source.

And now permit me through the medium of this letter
to tender my unfeigned thanks to you for your friendship.
If a request dictated by sincerity can with propriety be granted,
I would ask an answer to this letter.
Advice coming from a source +++[+++proved]
profitable by experience, will be received by your friend with unfeigned satisfaction,
and I should request it the more,
on account of the disinterested source from which it emanates.

Farewell.
May peace, productive of plenty, long bless our happy land; and may you, my friend,
live to glorify your Creator through the latter periods of your life,
and finally enjoy everlasting glory, through a Redeemer.

[.signed-section-closing]
Permit me to subscribe myself your grateful friend,

[.signed-section-signature]
A+++.+++ C. L.

[.signed-section-context-close]
Cincinnati, Ohio

--

[.offset]
To this letter Rebecca Hubbs returned an answer, only a part of which has been preserved,
viz.:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Woodstown, Second month, 14th, 1816.

[.salutation]
Respected Friend,

I received thy letter, dated First month, 6th,
and willingly devote a little of my time to comply with thy request.
But I have not the tongue of the learned, nor the pen of a ready writer,
to convey my mind to any, either by word or writing,
and must desire thy favorable construction of my letter while I
impart a little of my mind to thee in the simplicity of Truth.

The delights of this world, in years past,
very much estranged my mind from the subjects that
ought to have engaged my attention every day,
and I may say with the Psalmist, that '`before I was afflicted,
I went astray.`' But having obtained mercy from the Lord,
through the redeeming love of his dear Son,
I am in duty bound to speak well of his excellent name;
though at times I am beset with trials as on every hand,
while called upon to tread with awe on sacred ground;
being truly sensible I have nothing of my own to boast of,
save weaknesses and infirmities.

The feelings excited in my heart, while passing to and fro in your land,
were too deeply impressive to be easily erased.
War and rumors of war sounded in every quarter.
I think I shall ever remember, while memory remains,
something of the weight of exercise which my mind passed through,
and the feelings of pity which, unsought for,
came upon me for the poor military men in the field and elsewhere; though many of them,
through the power of habit, seemed indisposed to that which is good.
But "`to err is human; to forgive,
divine;`' and under a sense of the love of God to souls universally,
my spirit often breathed in secret supplication to God that the blessing of preservation,
and the extension of Divine mercy, might attend them,
as I have been passing about among them.

And although I and my fellow travellers, Zionward, through this world of uncertainties,
may be accounted fools or despised; and though, as I have learned,
bonds and afflictions betide the gospel, yet I rejoice in suffering;
and still desire in humble dedication to bear the
cross of Christ in obedience to the Divine will.
I hope thou wilt excuse my freedom if I mention that at the time I saw thee in Chillicothe,
at the house of B. H.,
I viewed thee as one whose greatest concern and exercise
of mind were in a degree hid from human eyes,
and fully known only to the Lord and thy own soul.
A secret language did bespeak to my mind that the Lord had dealt bountifully with thee,
and the desire accompanied,
that the excellent talents committed to thy trust
might not be wasted in the field of battle.
And now mayst thou not fall a victim to vanity, false pleasure, ambition, or avarice,
which,
alas! is the case with many who suffer their minds
to be taken captive by the spirit of this world.

May thy talents be occupied in and according to the Divine will;
and when we adopt this course, and pursue it,
however the natural bearing of the inclination may oppose,
yet having the full assent of the understanding in the all important work of salvation,
the inclination is often made quiescent, and the spirit is forming for the skies,
which is indeed the one thing needful; for here we have no continuing city.

What will it avail any to have a name enrolled in the book of fame,
if it is not written in the Lamb`'s book of life?
I wish thee every spiritual blessing and every temporal one that
may be consistent with thy advancement in best things.
I write not as supposing that anything can flow from my pen that will be new to thee.
I am a weak vessel, but knowledge is not wanting to thee.
I find it needful to be daily on the watch-tower,
lest worldly cares and the concerns of time and sense beguile me of that reward
which is in store for the righteous--for those that are laboring above every
other consideration to be redeemed from the bondage and the influence of corruption,
so as to escape the pollutions of this world, and in the end receive a crown immortal.

--

This devoted and faithful servant was frequently engaged in travelling abroad,
visiting the meetings of Friends,
and appointing meetings among those not in profession with us,
a service in which her labors were very acceptable.
Her mind was remarkably clothed with Divine love and charity,
under the softening and expanding influence of which she
was preparing to unite with and embrace the good in all,
laboring in gospel love and authority to gather all to Christ Jesus,
the compassionate Saviour who laid down his life for all.

In 1816, she attended the Yearly Meeting of Baltimore,
and in 1819 obtained certificates to visit meetings in Warrington Quarterly Meeting,
a constituent branch of Baltimore Yearly Meeting
and also meetings in Bucks Quarterly Meeting,
a part of Philadelphia Yearly Meeting.
No memorandums respecting these journeys,
or of those performed during several years subsequent, appear to have been preserved;
and indeed all the record that can now be found respecting her labors in after-life,
consists of a few fragments.

On the breaking out of the difficulties in the Society
respecting the doctrines of Elias Hicks,^
footnote:[As early as 1819,
Elias Hicks had began to spread new and unsound doctrines
throughout the Society in America.
Though he spoke much of an "`inner light,`" and alleged
his teachings to be in agreement with early Quaker principles,
they were in fact very much at odds with the long-established
beliefs of the Society (and Christianity in general),
and so were rejected and disavowed by the prudent and faithful.
His eloquent sermons exalted a sort of spiritual religion,
speaking much of love for neighbors, abolition of slavery,
and other right-sounding concepts,
but he led his followers into a disregard for the Scriptures,
and a total denial of several fundamentals of Christianity--such as the incarnation,
virgin birth, and divinity of Christ, the atonement by the cross, the existence of Satan, etc.
He taught that Jesus Christ was nothing more than a good man who,
having followed the light of God, was endowed with divinity, often saying things like,
"`The same power that made Christ a Christian must make us Christians;
and the same power that saved him must save us.`"
Eventually,
Hicks and his followers caused the first of two great divisions in the Society of Friends,
disassociating from "`orthodox`" Quakers,
and initiating their own separatist society of "`Hicksite`" Quakers in 1827.]
the mind of Rebecca Hubbs was brought into deep exercise and mourning,
because several whom she had long known and loved embraced his views,
questioning the authority of Holy Scripture,
the divinity of our Lord and Saviour Jesus Christ, and his mediation, intercession,
and advocacy with the Father,
as well as the efficacy of his propitiatory sacrifice for the sins of the world.
Having been forgiven much herself,
and known in her own experience the preciousness of his love and mercy,
and the virtue of his holy offices, she was remarkable for her love of Him,
and humble reverence of his Divine character;
and when she found these were undervalued or set
aside by those she had been intimate with,
her sorrow was great.

The subject of this memoir was closely united in
gospel fellowship with that worthy minister,
our late beloved Friend, Sarah Scull.
They sat together for years in the meeting at Woodstown,
were sometimes associated in religious labors, both abroad and at home,
and largely participated in the sympathy of suffering
and exercise which attended the trials of their day.
The meek, patient,
and humble spirit of her valued friend was peculiarly
congenial with the feelings of Rebecca Hubbs;
and she was often cheered and helped on her way by
her sisterly encouragement and kind aid,
while her solid,
mature religious experience and sound judgment enabled her to offer judicious counsel,
which proved a word in season.
When it pleased the Lord to take this devoted servant to himself,
to rest from her labors, as the prospect of the solemn event drew near,
she still evinced the same Christian solicitude for her fellow-laborer,
who was to be left a little longer on the field of action,
proving that her friendship had its origin in that love which is stronger than death.
Rebecca Hubbs deeply felt the loss of her steadfast and faithful friend,
and though for a long time she could scarcely speak
of her removal without being affected to tears,
yet, in the full persuasion that her own loss was her friend`'s everlasting gain,
she was enabled to bow in submission to the will of Him who doeth all things well.

[.offset]
The following letter to Sarah Scull, though without date,
will be interesting to the reader, viz.:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

Often, very often, has my mind been turned towards thee,
in the remembrance of days past and gone, when in exercise and baptism,
in suffering and rejoicing, we have travailed together in oneness of spirit,
both in heights and in depths.
At these seasons I have been comforted with the assurance that no change
of circumstances would ever be able to dissolve our friendship,
the sweetness of which I desire ever to retain.
As our waning life shortens, as days, months, and years increase upon us,
so our past experience of either joys or sorrows wears away,
and we are called to press forward towards the mark for the prize of everlasting life.

I feel much unity with thee in thy prospect of religious service,
and have no doubt but thy dedication will enable thee to
return with sheaves of sweet peace as thy reward.

As for thy poor, unworthy R. H.,
I may say the salvation of souls is at heart and nearest to my best life;
but I often fear that my usefulness has been and ever will be unequal to my zeal;
and am ready to query, Have I ever known any good?
Is there any good in me?
It seems at times as if I were in the sides of the ship,
or at the bottom of the mountains, where the weeds are wrapped about my head.
But I desire to be silent and adore, yet at times am aroused to serious reflection,
where "`will this conflict between heaven and earth land me?

[verse]
____
"`My heart the wise pursuit approves,
But, oh! what toils oppose!`"
____

Dear Friend, when it fares well with thee, remember me,
and speak favorably for me to the King,
that He bring me out of prison in what ever way He sees meet,
whereby my soul may be preserved in safety, in the arms of tender mercy and Divine love.

[.signed-section-closing]
Thine affectionately,

[.signed-section-signature]
Rebecca Hubbs.

--

Although her husband`'s means were small,
and the charge of a large family and other circumstances
rendered it difficult for her to leave home,
yet when the call of duty was distinctly heard,
she gave up to it in humble faith that way would be made.
In the year 1829, she visited the meetings within Haddonfield, Burlington,
and Shrewsbury and Rahway Quarterly Meetings.

In the eleventh month, 1831, Rebecca Hubbs and Lydia Miller,
a valuable minister belonging to Salem meeting,
obtained the concurrence of their Monthly Meeting to pay
a religious visit to the meetings constituting Concord,
Caln, and the Western Quarters,
and soon after set out on the journey accompanied by Samuel Abbott,
an elder of Salem meeting.
The weather was unusually cold and stormy, and considerable sickness prevailed.
Lydia Miller was taken with what seemed to be the prevailing distemper,
and after some weeks`' illness at the house of the late Joseph Pennell, of Middletown,
Delaware county, Pa., where she was tenderly and kindly nursed and cared for,
departed this life in great peace and quietude, trusting in the mercy of her Saviour.
Samuel Abbott and Rebecca Hubbs were also sick,
and the further prosecution of the visit at that time had to be given up.

Rebecca preserved some memorandums, from which the following extracts are made, viz:
Writing respecting one meeting, she says:

"`Words fitly spoken are '`like apples of gold in pictures of silver,`'
and tend to the honor of our Holy Redeemer.
In this meeting, I believe I spoke to the people without feeling enough of the woe,
if I did not.
This, I am sensible, is unsafe,
and may be compared to weighing anchor while the water is yet shallow.
None but the true Shepherd can hand forth the bread,
and rightly command to distribute it to the people,
and then only can it contribute to the nourishment of the spiritual life.
After this meeting, went to J. E.`'s, and thence to Chester meeting,
in which I was drawn forth to illustrate the Christian`'s
pilgrimage by the similitude of the outward creation,
as said the apostle,
'`The invisible things of God from the creation of the world are clearly seen,
being understood by the things that are made.`' I had also to show that
though no affliction for the present seemeth joyous but rather grievous,
nevertheless it yieldeth the peaceable fruits of
righteousness to him that is rightly exercised thereby.
Thus our trials often prove blessings in disguise,
and are made to work for the humble and resigned
soul a far more exceeding and eternal weight of glory,
while we look not at the things that are seen, "`but at the things which are not seen,
and which are eternal.

"`Went that afternoon with J. M. and wife,
who kindly came to accompany us to their dwelling,
where we spent an agreeable evening together.
The next morning (Seventh-day) my dear companion, Lydia Miller, was taken sick.
There was a meeting appointed for that afternoon,
and the weather being very cold and stormy with high wind,
it was a trial to me to set out, because of the great inclemency of the weather;
yet this seemed as nothing compared with the trial of leaving dear Lydia,
who was too poorly to go;
but as her disease was thought to be only the prevailing influenza,
I was hopeful that I should meet her again next day.
Our friend, J. M., accompanied Samuel Abbott and myself to Chichester meeting,
which was small,
yet we had evidence of the firmness and allegiance of some to Jesus of Nazareth,
and my concern was,
that the rising generation might be valiant for the Truth upon the earth.

"`First-day.
Went to Middletown meeting, where was a pretty large gathering of people,
and I thought it was owned by the great Shepherd of Israel,
who careth for the whole flock and family of mankind.
In the afternoon, went to the house of Joseph Pennell,
where towards evening came J. M. with my dear companion.
We were glad to see each other, and as we met, she said, '`O Rebecca,
how I wanted to be with thee again.`'

"`Second-day morning.
Lydia was more unwell,
and I was led to view it as an unsafe practice to appoint many meetings ahead,
as there were still two laid out for us to attend.
Our kind friend and companion, S. Abbott, being also sick this morning,
Joseph Pennell took me to the appointed meeting at Concord,
after which Abraham Sharpless very kindly invited us to his house,
saying he felt almost acquainted with us, as his wife was a near relation of our friend,
Elizabeth W. Miller, of Salem.
Returned to J. Pennell`'s, and found dear Lydia no worse,
and felt a hope that in a few days we might go on together.
S+++.+++ Abbott feeling better, in the afternoon we went towards Birmingham,
the next appointed meeting, and lodged at the house of N. S.

"`Third-day.
S+++.+++ Abbott was very sick, and our friend N. S. went with me to Birmingham.
As I had left both my companions in travel sick behind me,
my mind was deeply humbled and bowed very low,
yet I felt no sorrow or regret at my movements thus far,
but committed each one to the Lord, who could bear up our heads above the billows.
On returning from meeting, N. S. said to me, '`Well, Rebecca,
though sickness or whatever else may come, I feel assured of one thing, and that is,
thou wast in thy right place today;`' and now having
attended the last of the meetings appointed for us,
I felt glad, expecting soon to be with dear Lydia,
and not to have to leave her again while sick.

"`On our return to N. S.`'s, I found Samuel very ill,
much more so than when we left him in the morning,
and while I was preparing to go to J. Pennell`'s, he sent for me,
and desired I would not leave him that night, as he wished me to witness his will,
which he expected to have executed that evening, and as he and I were both from Jersey,
he thought it would be better for me to be a witness.
His daughter had been sent for to Westtown school to see him.

"`Fourth-day.
I returned to J. Pennell`'s, and found Lydia much the same; had a doctor attending her,
and was carefully nursed.
I stayed with her the rest of the week, which was a great satisfaction to me,
and I believe to both of us.
She was in the enjoyment of sweet peace, such peace as this world cannot give.
Sometimes I sat by her bedside in solemn silence, and some times would read to her,
and on one occasion she asked me to read a chapter, saying,
'`Is there not a passage of Scripture which says, Love not the world?
and does it not say also,
neither the things that are in the world?`' I found
and read it in one of the epistles of St. John.

"`Abraham Pennell, a valuable elder of Middletown meeting,
encouraged me to visit what meetings I could,
saying that Lydia would be well attended upon,
and that a way was open for me to go forward, and Mary Pennell would accompany me.

"`First-day morning.
Attended Middletown meeting, and in the afternoon with George Smedley,
and Joseph and Mary Pennell, set out for Wilmington.
Before starting, I sat in Lydia`'s room,
and at parting was bowed in supplication at her bedside,
where we made our appeal to Divine goodness, who seeth the hearts of all people,
that it was purely from a sense of duty that we thus
yielded ourselves up in obedience to Him.
On my leaving, she said, '`I am glad thou art going to Wilmington,
and be sure to be obedient when thou art there.`'
Whenever I recur to my parting with her at that time,
had I been certain I should never see her again on this side the grave,
I believe we could not have had a better parting.

"`Attended the Monthly Meeting held at Wilmington,
where I neither said nor thought any thing about my minute,
which I ought to have presented.
After it was over, proceeded to Concord to the house of N. S.,
and the weather being severely cold, I was taken with a hard chill,
and was soon very sick, being assiduously attended by Dr. M. by night and day.
ever to be remembered by me with gratitude was the kindness of my dear friend,
Lydia Sharpless, both in nursing me and in other ways,
and other Friends also were truly kind to me.
Samuel Abbott soon began to mend, and in a little while was able to return home;
but Lydia and I continued very ill, and though four or five miles apart,
yet through the kind attention of Friends we heard from one another nearly every day.
I had no expectation of my own recovery, and my husband being informed of my illness,
came immediately to me.

"`One night when all was still, as I lay awake,
there appeared to my sight plainly a remarkable vision.
I looked earnestly upon it,
and felt that it was permitted to give me warning of the near approach of death.
I trembled and was grieved, yet felt comforted that it was an appearance of Light.
Soon after this, Lydia Sharpless came into my room, and I told her of it,
and that it was to me a clear evidence of death, and that I thought I should soon die.
She replied, '`I think it is not on thy account;
but I must now tell thee that Lydia is very low, if not already gone,
and I do not know but this has been permitted on her account,
to let thee know that all is well with her.
Do not grieve.`' Dear Lydia Miller was indeed removed from all
the trials and afflictions of the church militant here on earth,
where bonds and afflictions abide us,
and is gone to join the church triumphant in heaven.
Lydia Miller deceased the 6th of First month, 1832.

"`When I was sufficiently recovered, I returned home with my husband,
but my mind seemed dead to this world, and all the things that are in it;
and when permitted to experience a revival of the Divine life,
the concern for which I had obtained a minute from my friends at home revived with it,
and my heart was clothed with love.
I mentioned my concern to proceed in the accomplishment of the visit, and my friends,
Rhoda Denn and Caspar Wistar, gave up to accompany me.
We had the unity of our Monthly Meeting, and were favored with health while absent.
After visiting nearly all the remaining meetings of the three Quarterly Meetings,
I returned home, and had great peace and satisfaction.`"

[.offset]
Besides the above brief notice, she has left some memorandums of this second visit,
of which the following are a part, viz.:

"`Fifth month 23rd, 1832.
Left home and crossed over to Wilmington, and next day attended Western Select Quarterly,
where was a part of the Yearly Meeting`'s committee,
among whom I felt myself as a grasshopper yet sheltered among the green leaves.
The Quarterly Meeting was a favored season,
and after it we went home with a Friend whose family, though much afflicted, were,
I believe, enrolled among the righteous.

"`25th. Had an appointed meeting at London Grove, which was well attended.
Much exercise fell to my lot, and I was engaged in the ability given me,
to exalt the Divine power and merits of our blessed Redeemer,
his mediatorial office and his sanctifying power,
as altogether sufficient to carry on and complete the restoration and full salvation
of all those who come unto Him in their hearts with true penitence,
and a firm belief that He can forgive their sins.
The Friend with whom we dined, informed me that a person of much note in the world,
a member of the legislature, said after the meeting, he was glad he was there,
and that the doctrine delivered was such as no Christian could find fault with.
We parted with the Friend in much love,
and he remarked with tears that he believed this meeting was among the right things.

"`26th. Attended Kennett meeting,
and in the afternoon had an appointed meeting in a private dwelling.
Several neighbors came in, and I had to revive the precious word of ancient promise,
--'`The wilderness and the solitary place shall be glad for them,
and the desert shall rejoice and blossom as the rose;`'
and Rhoda added a concurrent testimony.
We were comforted together in our silent waiting before Him, who is forever worthy,
and I thought, Oh, how precious is the unity of the Spirit.

"`27th. Were at Hockesson meeting,
where I was reminded of the gentle and innocent nature of the dove,
by which Noah was informed that the waters were assuaged from off the earth,
and had to recommend it.
At the Friend`'s house, where we lodged that night, we had a religious opportunity,
in which my companion had to impart counsel to the family.
My exercise was for a young man from England,
who was there learning the business of farming,
reminding him of the covenant of the patriarch in ancient days,
when he was leaving his kindred and his country, viz.: If God will be with me,
and will keep me in this way that I go,
and will give me bread to eat and raiment to put on, &hellip; then shall the Lord be my God, etc.

"`28th. At Spencer`'s meeting where I thought I got along in rather a hobbling way,
having very close exercise and trying work.
I had to speak of the falling away of some, and the blindness in part which,
the apostle said, happened to Israel:
also of our Saviour`'s description of what it was that defiled a man.
At this meeting Friends and the separatists met together.

"`29th. At New Garden meeting, where my mind was soon turned to Him,
who is the Author of life and of all our many blessings,
and I was led to revive the expression of the Psalmist, '`O Lord,
our Lord! how excellent is thy Name in all the earth!
who hast set thy glory above the heavens,`' etc.
I had also to speak of the faith and faithfulness of holy Stephen, the martyr,
and of Paul`'s being converted by the power of Christ`'s Spirit
from a persecutor to become a chosen vessel to publish his gospel.
Friends said they thought we were favored with a good meeting.

"`Next day attended West Grove meeting, where my companion was engaged in prayer.
My state for a time was like that of the heath in
the desert that knows not when good cometh.
But at length I had to mention that I was the companion of those
who were so sensible of their own weakness and unworthiness,
and of their poor, dependent state,
that they could in heart acknowledge that they had nothing to boast of but infirmities;
whom I desired to encourage.
After meeting, went to our friends,
William and Hannah Jackson`'s. William was very weak and infirm,
but alive and green in the sweetness and power of Truth.
They live in much simplicity and plainness, and are both above eighty years of age;
and in feeling their redeemed state, I said in my heart,
'`let me die the death of the righteous, and let my last end be like theirs.`'

"`I had a conversation with a Hicksite, who said,
'`I believe Christ gave his life for us, that is,
his whole life was entirely devoted to doing good
for us.`' I replied that there was more than that,
and more than mere example in the doctrine of Christ`'s propitiation.
She said, '`We must do our duty as He did his.`' I said,
'`The Scribes and Pharisees kept the moral law, but our Saviour said,
except your righteousness exceed the righteousness of the Scribes and Pharisees,
ye can in no wise enter into the kingdom of heaven.
That to be clothed with Christ`'s righteousness, it is needful for us to believe in Him;
and to become new creatures,
which we can only experience by and through Christ Jesus our Helper and Redeemer,
by his quickening power and life-giving spirit, illuminating our dark understandings,
purifying our hearts,
and converting us from a state of nature to a state of grace.`'
We parted from each other with tender regard.`"

[.offset]
After attending meetings at Fallowfield and Columbia,
she had an appointed meeting at Lancaster, of which she writes:

"`We dined with our valued friend, Hannah Gibbons,
and I had to propose a meeting being appointed at Lancaster,
which it was a great trial to me to mention.
My companions sympathized with me in the baptism I had to pass through,
and Abraham Gibbons being sent for, the proposal was solidly considered,
and Abraham said he would take all the necessary care in giving notice, etc.
When we reached the town, we were met by several Friends, who had come to be with us,
of which I was very glad.
The house was filled with people, and many who came could not find seats.
As I took my seat, and beheld such a large company, the words arose in my heart,
'`here is the wood and the fire,
but where is the lamb for the burnt-offering,`' feeling low and poor.
But my heart was soon warmed with gospel love, and tears fell from my eyes;
and I had first to mention that great and worthy passage of Holy Scripture,
'`God so loved the world that He gave his only begotten Son,
that whosoever believeth in Him should not perish, but have everlasting life.
For God sent not his Son into the world to condemn the world,
but that the world through Him might be saved.`' Many appeared very serious,
an awful silence soon spread over the meeting,
and help was given in the needful time both to visitors and visited.
There was such a solemn stillness nearly all the time of the meeting,
that it was evidently not of man but of the Lord, and unto Him be all praise given.
After it was over, I felt myself a poor, unworthy one, like a pelican in the wilderness,
but was soon surrounded by the people, several of whom thanked us for coming among them,
and with expressions of tenderness and love desired a blessing for us,
saying their hearts had been made glad that day.
After we got to the inn, one of the Friends of the neighborhood remarked, '`Oh,
what a favor there has not been such a meeting here for many years.`' We had many proofs
of the kindness and good feelings of the people of Lancaster towards Friends,
and as some of the most respectable of the inhabitants were at the meeting,
I was truly glad.

"`Second-day.
Rode to Lampeter meeting, where my companion bore a short but good testimony,
and I had a little to add from the words:
'`It is better to go to the house of mourning than to go to the house of feasting.`'`"

[.offset]
After being at Bart meeting, they attended the Monthly Meeting at Sadsbury,
of which Rebecca writes:

"`There being many of the elderly part of the Society there,
I felt cautious of taking up the time, or intruding upon them,
and mentioned that my heart`'s desire and prayer to God was,
that the aged ones who had known the Lord to be their morning light,
the stay of their youth and meridian day, and who,
in looking back over their spiritual warfare, can say with David, '`Thou, O Lord,
hast covered my head in the day of battle,`' might continue steadfast unto the end,
and joyfully experience Him to be their refuge,
the staff of their old age and their evening song.

"`Fourth-day.
Went to east Caln meeting,
where I was engaged in setting forth the truth that '`the world
by wisdom knew not God,`" and that it is only as we learn of Christ,
the wisdom which cometh from above, that we can become wise unto salvation.
My companion spoke of the necessity of faith in Jesus Christ,
mentioning the centurion`'s firm belief that He could heal his servant.
We went to dine with a Friend who has great possessions,
and such are in danger of hiding their Lord`'s talent in the earth.
But as temporal riches are uncertain, and often make to themselves wings, and fly away,
it is great wisdom to be striving to become new creatures,
whose trust is not in uncertain riches, but in the living God,
and to be laying up treasure in heaven.

"`Here I met with a young Friend,
whose mother and other near relations had gone with the separatists.
I had some solid conversation with him, in the course of which he said,
'`If the devil can but get us, he cares not by what means;
whether he beguile and deceive us; whether he cast us down,
or raise our minds above the true witness.`'

"`Fifth-day.
At Caln meeting, where I felt very comfortable in the revival and mention of the passage,
'`Then they that feared the Lord spake often one to another,
and the Lord hearkened and heard it:
and a book of remembrance was written before him for them that feared the Lord,
and that thought upon his Name.
And they shall be mine, saith the Lord of hosts, in that day when I make up my jewels,
and I will spare them as a man spareth his own son that serveth him.
Then shall ye return and discern between the righteous and the wicked,
between him that serveth God and him that serveth Him not.`'

"`Sixth-day.
Attended east Sadbury meeting, where was a burial, and after it was over,
the very large company attending it came into the meeting, where we had a solemn time.
I was led to hold up the important truth of Holy Scripture,
that '`by one man sin entered into the world, and death by sin,
and so death passed upon all men,
for that all have sinned.`' But not withstanding
such was the sad state of mankind in the fall,
through Divine goodness and mercy to man, a way of restoration was provided,
and through the obedience of One,
the free gift of grace came upon all men unto justification of life;
that we might joy in God through our Lord Jesus Christ,
by whom we have now received the atonement.
Thus might we be prepared for a happy resurrection,
and as through the goodness of our great Creator, we esteem it a privilege to live,
we should thus come to esteem it a glorious privilege to die.

"`On Seventh-day, the 9th of Sixth month, set off for Robeson or the Forest meeting,
twenty miles distant, which we attended on First-day.
Many more came to it than I expected to see, and I admired where they came from.
I revived the saying of the prophet Isaiah, '`Hear, O heavens, and give ear, O earth,
for the Lord hath spoken.
I have nourished and brought up children, and they have rebelled against me.
The ox knoweth his owner, and the ass his master`'s crib; but Israel doth not know,
my people doth not consider.`' I then pointed to Christ Jesus the Saviour,
in whom is the availing help of all to bring them out of this lapsed condition.
My companion also had a short but sweet testimony.
After meeting, the people were very kind, and showed us much respect;
one woman particularly, who wore gay apparel, was affected to tears,
and I thought she had been with Jesus, for her speech betrayed her.
Many Friends came to the house where we dined, and before we left,
we had a tender parting opportunity.

"`As we proceeded towards the next meeting,
the sun shone brightly on the green tops of the Warwick hills and the Welsh mountains,
making them beautiful to behold, while the sight of the cattle feeding upon their sides,
and of the rich pastures in the valleys as we passed along, were truly delightful;
and I was reminded of the text, '`The cattle upon a thousand hills`' are his.

"`Second-day.
At Nantmeal meeting, it seemed hard work to find the stepping-stones,
and to keep upon them.
I was engaged to invite all to endeavor to know for
themselves Jesus Christ and Him crucified.

"`Third-day.
Was at Uwchlan, and Fourth day, at Downingtown meeting.
After the latter, a Friend, in the station of elder, said to me, '`We have had a quiet,
solemn meeting,
and I have thought of the apostle when he said he was comforted by the coming of Titus,
and I can say I have been comforted by your visit
to us.`' We went on to Moses Bailey`'s near Bradford,
and being very much fatigued, and many discouragements coming over my mind,
I slept but little.

"`Fifth-day.
We were at Bradford meeting,
where I was made renewedly sensible that bonds and afflictions abide the gospel messengers;
and after a season of waiting, I was engaged in speaking on the saying of the apostle:
"`If in this life only we have hope in Christ, we are of all men most miserable.`"
In the afternoon, accompanied by a number of Friends,
went on to a meeting at West Chester, where was a mixed company of different persuasions.

"`Sixth-day.
Were at Goshen meeting; a large number of persons attended,
and I was engaged among them in commenting on the remarkable conversion of Saul,
at whose feet the witnesses against the faithful martyr, Stephen,
laid down their clothes.
Dined with Abraham Hibberd, a worthy minister,
who inquired of me if I remembered a meeting I once had in Chambersburg,
of which he had heard when passing that way about two weeks afterwards.
He gave me some interesting information respecting a family of Friends I visited,
not far from those who have passed through much suffering.
The man was guide for our company among the mountains,
where we stopped at different towns,
and held meetings with the people to good satisfaction.
His wife went with the separatists as long as she could;
and one day she came home in haste from one of their meetings, and said to him,
she had but escaped from among them with her life.
She then called all her family and children together,
and they sat down to wait upon the Lord,
and as they were far from any meeting of Friends,
they continued to hold a meeting in their own house.
In the afternoon attended Whiteland meeting,
and though there were not many Friends there, yet to me it was a very comfort able time.

"`Proceeding on our journey, we put up for the night.
The Friends dressed plainly; but when I went into their house,
and saw the splendid and showy furniture, I said in my heart,
if those people should put on their caps and feathers, and other gay attire,
it would but correspond with the grandeur of their dwelling.

"`Seventh-day afternoon.
Were at Willistown, and thence to Joseph Rhoads;
and this being one of the houses where dear Lydia
Miller and I had been on my former journey,
everything connected with it was brought fresh to my mind,
and I could not repress my tears.

"`Next day, went to Darby meeting, where I had to exhort Friends, if riches increased,
not to set their hearts upon them, but lay up their treasure in heaven.
Afternoon, had a meeting at Chester,
and my companions and I concluded that we had the best wine at the last.
Friends from several meetings came to be with us, and it proved a time of favor.`"

[.small-break]
'''

They returned home from this place,
and in returning her certificate to her Monthly Meeting,
she said she had been enabled to perform the duty to the peace of her own mind.

In 1833, she obtained the unity of her Monthly Meeting,
in a prospect of attending the Yearly Meeting of Baltimore,
and appointing meetings among Friends and others on the way, going and returning,
a service which she was strengthened to accomplish to good satisfaction.
Respecting one of the meetings she was at during this journey, she says:

[.small-break]
'''

"`Here I was led to hold up the convincing and converting power of Truth on the mind,
to lead man out of darkness into the marvellous light of the Lord,
concluding the meeting with solemn supplication for the remnant in this place,
whose zeal has led them to build a new meetinghouse.`"

[.small-break]
'''

She also visited Friends and others residing at Great and Little egg Harbor in 1835,
and in 1837 was liberated to attend the Yearly Meetings
of New York and New England and meetings on the way.
Of this journey she says:

[.small-break]
'''

"`Fifth month, 24th, 1837.
Left home under heavy discouragements, and as I rode on my way,
my troubled mind was bowed down; but after a time sweet melody broke forth in my heart,
with mental prayer and praises to the Lord,
and my reliance on the arm of his Divine power was renewed.

"`Landed at New York on Sixth-day,
and on Seventh-day attended the Yearly Meeting of Ministers and elders,
where many strangers were present, with certificates and minutes.
A committee was appointed to have the oversight of
the public meetings for worship through the week,
and I had to revive the language, '`except the Lord keep the city,
the watchman waketh but in vain.`'

"`In the meeting on First-day afternoon,
I remembered Him who had been my Helper hereto fore,
and cast in my little mite of testimony to the excellency of Jesus Christ our holy Redeemer.

"`In the sitting of the Yearly Meeting on Third day,
the subject of slavery was spread before us,
by the reading of a document sent in from the men, and much was said on it.
I cast in my mite, observing that the Lord said to his servant Moses,
"`I have seen the afflictions of my people,
and am come down to deliver them;`' which He did in his own time and way,
with a high hand and an outstretched arm.
And as it is not in man that walketh to direct his own steps aright,
so the important subject of the freedom of the African race
cannot be brought about but by the help of his power,
who covereth himself with light as with a garment,
and walketh upon the wings of the wind.
That I also had been in the land of slaves, and while I felt for them,
I also pitied their masters; one of whom said to me,
'`We shall never be as happy in this land as you are in yours, and the reason of it is,
that we have so many slaves,
and we know not what to do with them.`' I said it was a very important
thing to know the right time to act in a right concern,
and desired that the committee appointed in the case might seek in mental prayer the
proper counsel of Him who is for a spirit of judgment to those that sit in judgment,
that they might know when to go forward and when to stand still.
After clearing myself, my mind seemed released from a heavy weight, and after meeting,
a worthy minister said to me '`Rebecca,
it was worth thy while to come all the way to New York,
if thou did no more than speak to the subject of slavery--there
is indeed a right time for right things.`'

"`Fifth-day.
Attended the closing sitting of the Select Yearly Meeting,
and had to mention that the effectual fervent prayer of the righteous man availeth much,
desiring we might have a place and interest in one another`'s prayers,
when far separated, observing that this was the case with Boaz and his reapers,
who craved a blessing on each other.
He saluted them with '`The Lord be with you,`' and they answered,
'`The Lord bless thee.`'

"`Sixth-day.
An address to the people of the United States on the subject
of slavery was brought in from men`'s meeting,
and read.
Our dear friend, Elizabeth Coggeshall, in a very feeling manner,
spoke of the exercise she had felt that, while caring for the African race,
we might not forget the poor Indians, natives of the soil on which we tread,
and are faring bountifully from the produce of land once possessed by their fathers,
while they, poor creatures, are driven almost from the face of the earth,
observing that One is our Father in heaven,
and all equally the objects of his tender mercy.
Another Friend desired that we might look to the
condition of many of the members of our own Society,
especially in remote parts, where there was room for the benevolence of Friends.

"`At the close, Elizabeth Coggeshall bowed in fervent, solemn prayer; as much so,
I thought, as I had ever heard, and the clerk made an excellent closing minute.
We bade farewell, with prayers for each other`'s preservation when far separated.

"`After meeting, Elizabeth Coggeshall inquired if we were going over to Long Island.
I told her we had thought of doing so,
but it did not seem so clear to me as our first view of going on to Providence.
She said she was glad to hear it.
"`I will tell thee,`" said she,
"`what a person once told me at a time when I was in difficulty,
which was that whenever I was at a loss in such cases,
it was safest to keep to first openings, and I have often had to think of it since.`'`"

[.offset]
From New York they went into New England, to attend that Yearly Meeting.
Respecting a meeting at Coventry, Rhode Island, she says:

"`There were present a minister of the Presbyterian Society,
and a Baptist woman who seems drawing towards Friends; she came to me after meeting,
and expressed her satisfaction with it.
At Smithfield meeting we were helped and comforted by the presence of our divine Master,
and I was led to revive the circumstance of the poor toiling
disciples when in great peril on the boisterous sea,
and their earnest and availing cry to Jesus, '`Master,
carest thou not that we perish`" and He arose for their deliverance.
In the afternoon called to see a sick woman, who appeared near her close,
and the opportunity, though short, was a favored one.
She told us she felt very comfortable.
Attended Providence meeting,
where I was led to speak on those memorable words of the apostle Paul,
'`I am now ready to be offered, and the time of my departure is at hand.
I have fought a good fight; I have finished my course; I have kept the faith.
Henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, will give me at that day, and not to me only,
but unto all them also that love his appearing.`' Being about to leave this place,
I was favored with an evidence that it was right we had visited Friends and others hereaway;
and I had to invite those present frequently to consider the sufferings, even unto death,
which our predecessors in religious Society underwent in this land for
the faithful support of the principles and testimonies given us to uphold,
and the precious evidence they enjoyed even to their latest moments of the presence
and sweet influences of the Morning Star comforting and sustaining them.
After taking an affectionate leave of Friends,
as I rode along my cup overflowed with gratitude and peace.

"`As I entered the town of Fall River,
I felt my mind strongly drawn to have a public meeting that evening with the townspeople,
but it was so late we hardly expected it could be accomplished.
On consulting with C. S., it was concluded to try,
and though there was only one hour to give the notice, yet we had quite a large meeting,
and Friends said it was to good satisfaction.
My mind was exercised with the declaration, '`As I live, saith the Lord,
every knee shall bow to me, and every tongue shall confess to God.`' And again:
'`That at the name of Jesus every knee should bow, of things in heaven,
and things in earth, and things under the earth,
and that every tongue should confess that Jesus Christ is Lord to the
glory of God the Father.`' In this town there are many cotton factories,
and in the morning we went to one of them to see the process of printing calico.
The difficulties of the times are such that very
many poor people had to be turned out of employment,
and some of the mills were stopped.

"`Tiverton meeting was small,
but the danger of an unlawful love of lawful things impressed me,
and I had to revive the warning of the apostle James, where he says, '`Come now,
ye that say, today or tomorrow we will go into such a city, and continue there a year,
and buy and sell and get gain: whereas ye know not what shall be on the morrow.
For what is your life?
It is even a vapor that appeareth for a little time,
and then vanisheth away.`' And I was concerned to
show that as the nail cleaveth close to the joining,
so doth sin, without constant watchfulness, come in between the buyer and the seller.

"`Not far from this place we ascended a high hill,
and had a beautiful view of the surrounding country
on which the native Indians once lived and hunted,
and where hundreds of them were slain and buried by the whites.
Near Mount Hope was the place where their king, Philip, was treacherously captured,
as he lay with his little son asleep in his arms.
I was told that Annawon, the last Indian Sachem, a majestic-looking person,
was also taken near this place.
He asked for his life,
and on surrendering his arms as tokens of power to the white general,
he assured him he should not be slain.
But while he was absent from the camp, Annawon was shot dead by some of his men.
Such is the merciless cruelty and treachery of war!
Will not the Lord assuredly judge our land, sooner or later,
for the wrongs and cruelties inflicted on the Indians,
by which they are now almost driven from the face of the earth?

"`Went to Portsmouth to attend the Yearly Meeting of Ministers and elders.
At this meeting the names of a number of Friends were reported,
who had been newly appointed elders and acknowledged as ministers,
and I felt an earnest concern that, as they had thus been appointed,
they might also be anointed from on high,
and enabled to act aright in their responsible allotments.

"`First-day morning.
Went to the public meeting at Newport,
and thought I had never before seen so large an assembly.
In the afternoon, we had a favored meeting,
in which several Friends were engaged in the ministry.`"

[.small-break]
'''

No further memorandums of this visit appear to have been made.
Soon after the Yearly Meeting closed, she and her companions returned home,
and in returning her minute to the following Monthly Meeting,
she stated that she had performed the service to the relief of her own mind.

In 1838, she visited the meetings of Haddonfield Quarterly,
and appointed some public meetings,
and in 1839 she had the unity of her Monthly and
Quarterly Meetings expressed in their minutes,
liberating her to attend the Yearly Meetings of Ohio and Indiana,
visit meetings on the way going and returning,
and appoint some for those not in profession with Friends.
She was absent from home on this journey about three months.
The memorandums respecting it are very few and short.
We extract the following, viz.:

[.small-break]
'''

"`On the 14th of eighth month, 1839, in much love and tenderness,
I took leave of my husband and family and went to our Select Quarterly Meeting,
where I was permitted to enjoy a favored season.
In the afternoon, I visited the congregation of the dead at the interment of a young man,
the only son of his parents.
It was given me on this solemn occasion to bear testimony
to the excellency of the gospel of our Lord Jesus Christ,
and I had much satisfaction in this little offering;
for though but few of the company present were members of our religious Society,
yet they were my fellow pilgrims.

"`15th. Attended the General Quarterly Meeting much bowed down in mind,
but was somewhat strengthened and comforted by the unity and sympathy
expressed by my beloved friends in the visit I had in prospect.

"`16th. Met my companions in travel, Charlotte N. Freedland and Samuel Allen,
and set out on our journey westward.

"`17th. Got to R. M.`'s, where we lodged.
His mother was in the 91st year of her age, and we were glad to see each other again;
she appeared alive in the precious cause of our blessed Redeemer.

"`18th. Went to Sadsbury meeting, where I was pleased to see some of the young people,
whose countenances bespoke that they were seeking Jesus.
In the afternoon, went to the house of a Friend,
one of whose sons had died that morning after a few days`' sickness.
I was engaged to advise his parents and brothers not to grieve too much,
and the latter particularly not to forget him too soon,
for I learned that he was a promising young man,
and a good example in the neighborhood and to those around him.

"`20th. Got to G. W.`'s, a Friend,
who was pilot for me over the mountains twenty years ago,
when I held meetings in the little towns on the way, at Chambersburg, McConnelstown,
Bedford, Huntington, and Carlisle, etc.,
which service has been lasting in my remembrance with great satisfaction,
even to this day.

"`21st. Had a meeting at Monallen, held in the house of G. W.,
who with his family were left very much alone at the time of the separation.
I thought our little company was owned by the presence of our dear Redeemer.`"

[.offset]
In crossing the mountains, she makes these reflections:

"`Oh, these lofty rocks and mountains, towering one above another,
with the stately trees growing upon them,
all placed in their proper form and allotments by the great Creator,
surely the sight of them is sufficient to make us both fear and praise the Lord,
who can indeed change the wilderness into a fruitful field.
When I travelled over these mountains twenty-five years ago,
we saw the tracks of wolves now and then crossing our road,
and the hunters with their long frocks and guns pursuing them, but now the sides,
and in some places even the tops, of the mountains are covered with excellent grain,
affording sustenance to man.
Surely the Lord`'s mercy is in every place.

"`At Bedford, called to see D. M. and wife.
She remembered my being there in my former journey, and having a meeting,
and visiting the prisoners in the goal.
She invited us to stay and have a meeting now, saying,
'`How I do want to hear a good Quaker sermon!

"`25th of the month.
Crossed the Alleghany Mountain,
said to be the highest land between the Lakes and the Gulf of Mexico;
passed through Somerset, and ascended about one mile on Laurel Hill,
where we put up much fatigued with our day`'s travel,
and discouraged by the people in the house and other causes.
Charlotte and I let fall a few tears, but my spirit was revived,
and my faith strengthened in thinking how the primitive believers
wandered about and dwelt in dens and caves of the earth,
and I said we will still trust in the name of the Lord our God.

"`27th. Left Robstown,
and had a delightful ride along the banks of the Monongahela River,
with the high bluffs on our right, and the stream on our left hand.
But the beauty of the scene could not prevent my thoughts
from dwelling upon the awful events long since past by,
when many persons were slain near here by the French and Indians.
One of our horses being sick, we came very slowly on to Washington, and lodged.

"`Next morning my mind was exercised with the prospect of having a meeting at this place.
Samuel Allen mentioned it to the landlord and a Methodist minister, who called in.
He was very kind and attentive to us;
said he knew the people would be pleased with the opportunity,
and that we should be welcome to their meetinghouse,
but the courthouse would be more central.
The meeting was appointed at early candle light, and was well attended, and, I thought,
favored with the owning of Truth, even the canopy of the Divine presence over us.
After it was over, our friend, the Methodist minister, said,
'`You have had a good collection, and I rejoice in the opportunity.`"
In walking to our lodgings, a nice woman stopped me, and said,
'`I have been with you at the meeting; I feel that I am your sister;
I hope I am your sister in Christ;`' truly I thought, '`One is your Master, even Christ,
and all ye are brethren.`'

"`28th. Left Washington,
and oh! the sweet peace that accompanied my mind as I rode on my way,
making melody in my heart unto the Lord,
though great had been my baptism before I yielded to this required duty.`"

[.small-break]
'''

Having reached Mount Pleasant, they attended the Yearly Meeting of Ohio.
On Second-day, being at the Boarding-school with upwards of one hundred Friends, she says:

[.small-break]
'''

"`All present were collected, and we had a favored, interesting meeting.
Daniel Wheeler and Jacob Green and other ministers were present,
and I witnessed the princes in our Israel riding as upon the king`'s horse,
and believe those also were remembered who were sitting as at the gate.

"`Fifth-day.
Meeting for worship was held at Mount Pleasant.
Daniel Wheeler had an excellent communication, in the course of which he said,
'`I have left all that is nearest and dearest to me in this world, to come among you,
and willingly would I travel from east to west, and from north to south,
old and gray-headed as I am,
if I might be made instrumental in turning any of my fellow-mortals
to the love of God.`' The meeting was gathered into solemn silence,
and after he closed, Jacob Green and others followed, and I bowed low in supplication.

"`Seventh-day.
Assembled for the closing sit ting of the Yearly Meeting,
and were visited in the women`'s apartment by Jacob Green and Daniel Wheeler,
both of whom spoke excellently.
Jacob reminded us that probably we should never again see our beloved brother,
Daniel Wheeler, who was about to return to his native land,
in consequence of the illness of his family.
I had to express the desire I felt that we might
all hold in remembrance the present visit,
and also our beloved brother,
who had been preserved in many perils by land and perils by sea;
and craved that the same Divine power which had attended him hitherto,
might still be continued, grant him a safe arrival on his native shores,
and when done with time, the enjoyment of everlasting glory through our holy Redeemer.`"

[.offset]
They left Mount Pleasant after the Yearly Meeting, and proceeded towards Indiana,
taking meetings on the way.
She writes:

"`15th of Ninth month.
Came to Pennsville meeting, where was a very large assembly,
and much exercise and labor in love fell to my lot from the passage
where our Saviour and his disciples ate with publicans and sinners,
and his words, "`They that are whole need not a physician; but they that are sick.
I came not to call the righteous,
but sinners to repentance.`' Here is a large Monthly Meeting of Friends,
where but a few years ago the country was all a forest.

"`16th. Went to Chesterfield, where was a large meeting,
and my mind was much exercised on several subjects.
After meeting, my dear companion said she thought we might set up our Ebenezer.

"`17th. Were at Plymouth, the last meeting in this settlement,
where are two Monthly Meetings, and three meetings for worship,
and now being about to leave them, we feel amply rewarded for visiting Friends here.

"`20th. Got to Chillicothe;
and my mind was much impressed with a concern to have a meeting,
though I endeavored to pass on without giving up to it, but could not do so peacefully;
and it was agreed to have a meeting at early candle-light, to be held in the courthouse,
as there were no Friends in the town.
We sat down before a large and respectable-looking company,
and after a short time the meeting settled into solid and solemn silence,
and was as still, I thought, as though all the people were Friends.
Divine help was afforded in the needful time, and the meeting ended, I hope,
to the praise of our Redeemer.
If the opportunity had a tendency to enliven the Christian hope of a single individual,
or to awaken any from the sleep of death, as the call went forth, '`Awake,
thou that sleepest, arise and shake thyself from the dust,
and Christ shall give thee light`' may all the praise
be given to our blessed and compassionate Redeemer.
After meeting, the people were kind and respectful, inviting us to stay with them,
but we excused ourselves.`"

[.offset]
They reached Richmond, Indiana, in time for the Yearly Meeting, which they attended,
and soon after it was over, turned their faces home ward.
She writes:

"`At Raysville, came to the house of J. P., who,
when I was in Ohio twenty-five years ago, very kindly gave up to pilot us,
and was in company with us several weeks, though not then a member.
I was glad to see him again; he is married, and has sons and daughters,
who are promising, and himself a valuable member of Society; he seemed glad to see me,
as he said it was to him like seeing a mother.

"`Attended Elmgrove meeting, where the spring of Divine life seemed very low,
yet I was glad to see an appearance of faithful standard-bearers being raised up.

"`First-day afternoon.
We had an appointed meeting at Indianapolis.
Quite a large company of Friends and others attended;
and I thought it a favored opportunity.
Sinners were called to repentance,
and encouragement offered to the righteous to hold on their way.
We were favored with a sweet evidence of the compassionate regard of our heavenly Father,
who hath begotten us again unto a lively hope by
the resurrection of Jesus Christ from the dead.

"`18th of Tenth month.
In the evening had a meeting with Friends and others at Waynesville, Ohio,
and felt thankful to the great Master for his help vouchsafed in the needful time.
Friends thought it a favored meeting, and very still for so large a company.

"`Sixth-day.
Had a meeting at New Brighton, Pa., which was, I thought, a very good one.
I had to speak respecting our Saviour Jesus Christ
being an offering for the sins of the whole world,
and that such was the virtue and efficacy of it,
being a sacrifice of a sweet-smelling savor to the Father,
that the effect of it reached back to the first transgression of man,
and forward to the end of time.
That all succeeding generations from the hour in which He suffered on the cross,
as well as all that went before,
are benefited by the atoning blood and merits of our Lord Jesus Christ,
through which all may be brought near unto the Father,
and by faith in and obedience to his dear Son, may,
through the operation of his Spirit in their hearts, become new creatures, created anew,
and raised from dead works to serve the living God.
A+++.+++ T. told me afterwards that there were several of the Hicksites at the meeting.`"

"`Eleventh month 4th, 1839.
Came to Laughlinstown,
a place I well remember when I travelled this way twenty-five years ago.
A company of soldiers marching from Pittsburg had stopped here,
and a woman in the house where we put up was grieving much on account of her son,
who was in the company, and going on to Baltimore, to meet the British.
We also passed the spot where the carriage of Micajah Collins and company was upset.
Solemn indeed were my feelings as I called to mind these things,
and remembered that nearly all who were in company
with me then are now gone from works to rewards,
and I am spared a little longer.
May I be prepared to go.`"

[.offset]
They proceeded directly home, without stop ping at any meeting.

In Ninth month, 1841,
she was liberated to visit the Quarterly Meetings of Bucks and Abington,
and the meetings composing them,
and also to appoint some meetings where no Friends reside.
She was strengthened to accomplish this service, much to the relief of her mind.
The last meeting was one appointed for the inhabitants near the Pennepack,
of which she says, "`It was attended by a considerable number of respectable people,
and my heart rejoiced under a fresh sense of the universal
love of God in and through his beloved Son,
Christ Jesus, who has been our Helper in this visit;
may all praise be ascribed unto his great Name.`"
In returning the minute granted her,
she said she had afresh experienced that every act of dedication to the will of the
great Head of the church is rewarded with the incomes of his enriching peace.

Advancing years had made considerable impression on her constitution,
and she sensibly felt the infirmities and weakness of age,
as well as many close trials and privations which fell to her lot.
But love to her heavenly Father,
and a fervent desire for the everlasting welfare of her fellow creatures,
seemed the prevailing clothing of her spirit.
Under the constraining influence of this love,
she believed herself again called to leave home in the service of the gospel,
and surrendering herself in obedience to what she believed to be the command of her Lord,
she had the unity of her Friends expressed in the minute of Salem Monthly Meeting,
to attend the Yearly Meeting to be held in Virginia in 1844,
to visit some of the meetings composing it,
and to appoint some among those not of our religious Society.
This was her last journey in the work of the ministry,
and she spoke of it afterwards as "`the evening sacrifice,`" the retrospect of which,
though deeply sensible she was indeed an unprofitable servant, afforded her much peace.
She makes the following memorandums respecting it, viz.:

[.small-break]
'''

"`Fourth month 20th, 1844.
Set out with my companion, Mary Carpenter, from Philadelphia,
and met Caspar Wistar at Wilmington.
Attended meeting there next day, where J. P. was favored in testimony,
and I added a little on the necessity there is to resist all evil, for Satan,
our adversary, goeth about like a roaring lion seeking whom he may devour,
and as a cunning serpent seeking whom he may deceive.
He was once an angel of light, and included among the '`all`' which God made,
and which He pronounced good, but by not keeping his first estate,
he fell through rebellion, and, from an angel of light,
became an angel of darkness and an enemy to all goodness.
But, though subject to his temptations, I had to set forth that by Christ Jesus,
the Saviour of the world, we may be delivered from the snares of the evil one,
and obtain eternal salvation,
where the wicked cease from troubling and the weary soul is at rest.

"`On Second-day morning, in company with several other Friends,
left Wilmington for Virginia, passed Elkton and Baltimore, and arrived at Washington,
where I greatly admired to see the change since I was there in 1813.
Third day took steamboat, and went down the Potomac River,
passing Alexandria and Mount Wernon, and much beautiful scenery.
Landed at Aquia Creek, and saw at the hotel a poor slave handcuffed with irons;
his master, a well looking youth, took him in the cars as far as Fredericksburg.
I thought, there is a heaven,
where the prisoners rest together and hear not the voice of the oppressor.

"`Fourth-day.
Attended Caroline meeting, where were more persons than I expected to see,
and though it was unsettled for a time,
yet at length we were favored with some solemnity.

"`Sixth-day, 26th. Went to Cedar Creek, and afterwards to Walter Crew`'s house.
Thirty-one years ago this Friend was pilot for myself and my dear companion, Sarah Scull,
to some places hereaway, and went with us to James Madison,
then the President of the United States.
I was glad to see him once more, and after a favored religious opportunity in his family,
we parted in much Christian love.

"`First-day.
At Richmond meeting, where I was reminded of the Scripture declaration,
'`There is a spirit in man,
and the inspiration of the Almighty giveth them understanding.`'
I had to show that though this was in man,
yet it was not of man, but of God, who made him for a purpose of his own glory;
that through obedience thereto, he might glorify Him here on earth,
and be happy forever with Him hereafter.
I felt thankful for a renewed sense of Divine love shed abroad universally to all,
and I thought we were favored with a time of refreshing
from the presence of our holy Redeemer,
to whose great Name be praises given.

"`Second-day.
Left Richmond for Norfolk.
In passing down James River,
we were shown the place where the great Indian chief Powhattan lived, and also his grave,
marked by a large stone.
The spot where Captain John Smith first landed on Powhattan`'s land,
to wrest it from him, was also pointed out to us.
Near Jamestown we saw the remains of the first place of worship,
built by the white settlers in Virginia,
and said to be the oldest of the kind in the United States.

"`Fifth month, 1st. Went to the first meeting in North Carolina.
Here I was led to set forth the excellency of faith in Christ,
and the awful consequences of unbelief and irreligion,
on which I had to dwell to my own admiration.
While I was speaking, a man on horseback rode up to the meetinghouse,
and after sitting a few minutes on his horse, came into the house,
and stayed until the meeting closed,
when he came up and spoke to me kindly and to several other Friends.
We were afterwards informed that he held a great many slaves,
did not make any profession of religion, and seldom went to a place of worship.

"`2nd. Went to Symon`'s Creek meeting, where many were present,
and I thought we were favored with help from the great sanctuary,
and afresh strengthened out of Zion.
A little before the close,
a ministering Friend present arose and said he believed
we had been visited of the Lord this day,
and he wished all to be encouraged.

"`Seventh-day.
Were at Piney Woods Monthly Meeting,
where I was led to revive our Saviour`'s admonition to be at peace with all men, viz.:
'`If thou bring thy gift to the altar,
and there rememberest that thy brother hath aught against thee,
leave there thy gift before the altar, and go thy way;
first be reconciled to thy brother,
and then come and offer thy gift.`' Another Friend spoke on the same subject,
and I feared that between us both, our offerings were rather too much.
I felt much for Friends here in their lonely situation, there being so few left.

"`First-day.
At Piney Woods Particular Meeting, where was a large gathering,
most of them standing around the house, waiting for us, which seems to be the practice.
I was engaged in supplication, and afterwards, in much weakness, arose before them all,
with the saying of the apostle, '`The Jews require a sign,
and the Greeks seek after wisdom, but we preach Christ crucified,
unto the Jews a stumbling-block,
and unto the Greeks foolishness;`' showing that unto every one that believeth in Him,
He is the wisdom and power of God unto salvation.
Help from on high seemed afforded in the needful time.
My dear companion, Mary Carpenter, spoke to the colored people, of whom there were many.
They were very quiet, and behaved very well.
It was thought there were more than six hundred persons at this meeting.

"`Second-day morning.
Were at Wells`' meeting, and in the afternoon at Beach Spring,
and reached our lodgings just in time to escape a heavy
storm with thunder and lightning and strong wind,
by which many large trees were blown down.

"`Third-day.
Attended Rich Square, where our dear Friend, Richard Jordan, once belonged.
We were favored with a quiet, solemn season.

"`Fourth-day.
Started for Black Creek, in Virginia, and, on our way,
passed through a town called Jerusalem.
My heart was pained and grieved to see the very many slaves as we passed along.
This was the seat of the Southampton negro insurrection some years ago,
for which many of the slaves were shot or hung.
We were told several were shot under the large trees before
the door of the house where we stopped to bait.

"`Fifth month 8th, Fifth-day.
Attended Black Creek meeting, and went that afternoon twenty miles towards Gravelly Run.
Next day rode forty-five miles to the house of the late J. Butler,
who had died about four weeks before, and his widow was in grief for her loss.
At this place the Yearly Meeting of Virginia was once held, and many Friends lived here,
but now there is a great change.
Some have died, and some have left the land of slavery, so that very few are left.
The widow told me that her husband sat in the meetinghouse
alone on the First-day before he died,
and had frequently done so.
We seemed to be comforted together, and were solemnly reminded of our own mortality,
that we also must soon die, and be separated from all things here.

"`First-day.
Attended Gravelly Run meeting, and on Third-day were at Black Water,
many more persons attending than I expected to see.

"`Fourth-day.
At Western Branch, where was a large meetinghouse, but very few members.
Robert White, a firm member, had recently been removed by death.

"`Fifth-day.
Were at Johnson`'s, where I think we were favored with a very good meeting.
There was quite a large gathering, and I was led to speak from the words of David,
'`O Lord, our Lord, how excellent is thy name in all the earth,
who has set thy glory above the heavens.
Out of the mouth of babes and sucklings hast thou ordained strength,
because of thine enemies,`' etc.
The people were very attentive, and behaved solidly.

"`Sixth-day.
Attended the Quarterly Select Meeting at Summerton,
and in the afternoon the General Quarterly Meeting.`"

[.small-break]
'''

No further memorandums of this journey have come to hand.
She was favored to reach home in safety,
and returned her minute with the acknowledgment that the
performance of the service had afforded her solid satisfaction.
She afterwards at times alluded to it with the humble assurance that she
had endeavored to do the little which was required at her hands,
and that she had the gracious answer of "`Well done,`" from her Lord and Master.

Her health and strength began to decline,
but she was generally able to get to her own meeting,
and frequently to the Monthly Meeting at Salem, where she was a member.
She greatly enjoyed the society of her Friends,
and esteemed it a privilege to meet with them for the purpose of Divine worship,
often pressing through difficulties, and attending meetings under much bodily infirmity.
One of the last Monthly Meetings she was at, she appeared much enfeebled in body,
but very lively in her spirit, and, after a season of solemn, quiet waiting,
she arose with the words,
"`With desire have I desired to eat this passover with you before I suffer;`"
enlarging instructively on the mercy and goodness of the Redeemer,
and his willingness to furnish spiritual nourishment,
and to sup with the sincere waiting ones;
and intimating also the probability this might be
her last opportunity with her Friends in that capacity.

About two years before her close, she was attacked with paralysis,
of which she had repeated slight returns, gradually weakening her powers.
She bore the consequent suffering with meekness and patience;
retained her love and relish for the things pertaining to the kingdom of God,
and for her merciful Saviour,
who seemed dearer to her the nearer she approached to her mansion in heaven.
The company of her Friends afforded her much satisfaction,
and she generally greeted them with a cheerful smile
and a heart replenished with Divine love.
On the day previous to her close, taking leave of some of them,
she said very affectionately, "`Farewell in the Lord.
I trust the Lord will have mercy upon us all.`"

Thus, with humble composure and steadfast reliance on the mercy of God in Christ Jesus,
she gently and calmly met the solemn summons,
quietly departing on the morning of the 29th of Tenth month, 1852,
in the 80th year of her age, and, we doubt not,
is entered into the rest prepared for the righteous.

[.the-end]
The End
